"""Gmail Auto-Fetch Service — connects user Gmail, scans for CAS emails,
extracts PDF attachments, and feeds them into the CAS parser."""
import logging
import base64
import os
import warnings
from datetime import datetime, timezone
from google_auth_oauthlib.flow import Flow
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request as GoogleRequest
from googleapiclient.discovery import build

logger = logging.getLogger(__name__)

GMAIL_SCOPES = [
    "https://www.googleapis.com/auth/gmail.readonly",
    "openid",
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/userinfo.profile",
]

# CAS email detection patterns
CAS_SENDERS = [
    "nsdl-cas@nsdl.co.in", "nsdl", "cdsl", "cams", "kfintech", "karvy",
    "donotreply@camsonline.com", "donotreply@kfintech.com",
    "noreply@nsdl.co.in", "ecas@nsdl.co.in",
    "noreply@cdslindia.com", "edis@cdslindia.com",
]

CAS_SUBJECTS = [
    "consolidated account statement",
    "cas", "e-cas", "ecas",
    "account statement",
    "portfolio statement",
    "nsdl e-cas",
    "cdsl cas",
]


def create_gmail_flow(client_id: str, client_secret: str, redirect_uri: str) -> Flow:
    """Create Google OAuth flow for Gmail access."""
    return Flow.from_client_config(
        {
            "web": {
                "client_id": client_id,
                "client_secret": client_secret,
                "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                "token_uri": "https://oauth2.googleapis.com/token",
            }
        },
        scopes=GMAIL_SCOPES,
        redirect_uri=redirect_uri,
    )


def get_authorization_url(client_id: str, client_secret: str, redirect_uri: str, state: str) -> tuple:
    """Generate Google OAuth authorization URL for Gmail.
    Returns (url, code_verifier) — code_verifier must be stored and passed to exchange."""
    flow = create_gmail_flow(client_id, client_secret, redirect_uri)
    url, _ = flow.authorization_url(
        access_type="offline",
        prompt="consent",
        state=state,
        include_granted_scopes="true",
    )
    # Extract the code_verifier generated by the Flow (needed for PKCE)
    code_verifier = flow.code_verifier
    return url, code_verifier


def exchange_code_for_tokens(client_id: str, client_secret: str, redirect_uri: str, code: str, code_verifier: str = None) -> dict:
    """Exchange authorization code for tokens."""
    flow = create_gmail_flow(client_id, client_secret, redirect_uri)
    # Restore code_verifier for PKCE
    if code_verifier:
        flow.code_verifier = code_verifier
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        flow.fetch_token(code=code)

    creds = flow.credentials
    return {
        "access_token": creds.token,
        "refresh_token": creds.refresh_token,
        "token_uri": creds.token_uri,
        "client_id": creds.client_id,
        "client_secret": creds.client_secret,
        "expires_at": creds.expiry.replace(tzinfo=timezone.utc).isoformat() if creds.expiry else None,
    }


def get_gmail_credentials(token_doc: dict) -> Credentials:
    """Build Credentials object from stored token, refreshing if needed."""
    creds = Credentials(
        token=token_doc["access_token"],
        refresh_token=token_doc.get("refresh_token"),
        token_uri=token_doc.get("token_uri", "https://oauth2.googleapis.com/token"),
        client_id=token_doc["client_id"],
        client_secret=token_doc["client_secret"],
    )

    # Check expiry and refresh
    expires_at = token_doc.get("expires_at")
    if expires_at:
        if isinstance(expires_at, str):
            from dateutil.parser import parse as parse_date
            expires_at = parse_date(expires_at)
        if expires_at.tzinfo is None:
            expires_at = expires_at.replace(tzinfo=timezone.utc)
        if datetime.now(timezone.utc) >= expires_at:
            try:
                creds.refresh(GoogleRequest())
                logger.info("Gmail token refreshed successfully")
            except Exception as e:
                logger.error("Gmail token refresh failed: %s", e)
                raise

    return creds


def build_gmail_service(creds: Credentials):
    """Build Gmail API service."""
    return build("gmail", "v1", credentials=creds, cache_discovery=False)


# Preference order: lower index = higher priority.
# auto-import picks the highest-priority source that has a parseable email.
SOURCE_PRIORITY = ["nsdl", "cdsl", "cams", "kfintech"]

# One Gmail query per source — Gmail returns results newest-first so
# maxResults=3 gives us the 3 most recent emails per sender to maximise
# the chance of finding a PDF, without processing stale history.
_SOURCE_QUERIES: list[tuple[str, str]] = [
    ("nsdl",     "from:nsdl.co.in has:attachment filename:pdf"),
    ("nsdl",     "from:NSDL-CAS@nsdl.co.in has:attachment filename:pdf"),
    ("cdsl",     "from:cdslindia.com has:attachment filename:pdf"),
    ("cdsl",     "from:cdsl has:attachment filename:pdf"),
    ("cams",     "from:camsonline.com has:attachment filename:pdf"),
    ("cams",     "from:cams has:attachment filename:pdf"),
    ("kfintech", "from:kfintech.com has:attachment filename:pdf"),
    ("kfintech", "from:karvy has:attachment filename:pdf"),
]

# ── OAuth-verification sender bypass (TEST MAILBOXES ONLY) ─────────────────
# CAS statements arrive from fixed depository senders, so the scan above is
# sender-scoped. For OAuth-review *test* mailboxes we ALSO accept a CAS PDF
# from any sender, so a Google reviewer can drop a sample statement into the
# inbox from a normal account. Gated strictly to the *connected mailbox's own
# address* being in the allowlist below — a real user's scan is never touched.
# Extendable via the CAS_SCAN_BYPASS_EMAILS env (comma-separated).
# TODO: remove once Google OAuth verification is complete.
_DEFAULT_BYPASS_EMAILS = {"nnivesssh@gmail.com"}
_ANY_SENDER_QUERY: tuple[str, str] = ("upload", "has:attachment filename:pdf newer_than:2y")


def _bypass_emails() -> set:
    """Allowlist of mailboxes exempt from sender validation (test accounts)."""
    extra = os.environ.get("CAS_SCAN_BYPASS_EMAILS", "")
    return {e.lower() for e in _DEFAULT_BYPASS_EMAILS} | {
        e.strip().lower() for e in extra.split(",") if e.strip()
    }


def _connected_mailbox(service) -> str:
    """Address of the Gmail account being scanned — used only for the gate."""
    try:
        prof = service.users().getProfile(userId="me").execute()
        return (prof.get("emailAddress") or "").strip().lower()
    except Exception as e:  # noqa: BLE001 — a profile hiccup must never break scan
        logger.warning("getProfile failed during CAS scan: %s", type(e).__name__)
        return ""


def _scan_queries(service) -> list:
    """Sender-scoped CAS queries, plus an any-sender query ONLY when the
    connected mailbox is an allowlisted OAuth-review test account."""
    if _connected_mailbox(service) in _bypass_emails():
        logger.info("CAS sender-bypass ACTIVE for connected test mailbox")
        return [_ANY_SENDER_QUERY, *_SOURCE_QUERIES]
    return list(_SOURCE_QUERIES)


def _classify_source(sender: str, subject: str) -> str:
    """Return the canonical source key for an email."""
    s = sender.lower()
    if "nsdl" in s:
        return "nsdl"
    if "cdsl" in s or "cdslindia" in s:
        return "cdsl"
    if "cams" in s or "camsonline" in s:
        return "cams"
    if "kfintech" in s or "karvy" in s:
        return "kfintech"
    # Subject fallback
    subj = subject.lower()
    if "nsdl" in subj:
        return "nsdl"
    if "cdsl" in subj:
        return "cdsl"
    if "cams" in subj:
        return "cams"
    if "kfintech" in subj or "karvy" in subj:
        return "kfintech"
    return "unknown"


def _parse_email_date(date_str: str) -> datetime:
    """Parse an RFC 2822 email Date header to a UTC datetime."""
    try:
        from email.utils import parsedate_to_datetime
        dt = parsedate_to_datetime(date_str)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.astimezone(timezone.utc)
    except Exception:
        return datetime.min.replace(tzinfo=timezone.utc)


def scan_for_cas_emails(service, max_results: int = 30) -> list:  # noqa: ARG001 (max_results kept for API compat)
    """Scan Gmail for CAS emails.

    Returns at most one email per source (NSDL / CDSL / CAMS / KFintech),
    the most recent one with a PDF attachment, sorted by SOURCE_PRIORITY so
    callers can simply take the first item for the preferred source.
    """
    seen_ids: set[str] = set()
    # latest_by_source[source] = best email dict found so far
    latest_by_source: dict[str, dict] = {}

    for source, query in _scan_queries(service):
        try:
            results = service.users().messages().list(
                userId="me",
                q=query,
                maxResults=3,   # newest 3 per sender; first parseable wins
            ).execute()
        except Exception as e:
            logger.warning("Gmail search failed for query '%s': %s", query, e)
            continue

        for msg_meta in results.get("messages", []):
            if msg_meta["id"] in seen_ids:
                continue
            seen_ids.add(msg_meta["id"])

            # Skip if we already have a candidate for this source — Gmail
            # returns newest-first so the first PDF-bearing email wins.
            if source in latest_by_source:
                continue

            try:
                msg = service.users().messages().get(
                    userId="me", id=msg_meta["id"], format="full",
                ).execute()
            except Exception as e:
                logger.warning("Failed to fetch email %s: %s", msg_meta["id"], e)
                continue

            headers = {
                h["name"].lower(): h["value"]
                for h in msg.get("payload", {}).get("headers", [])
            }
            sender  = headers.get("from", "")
            subject = headers.get("subject", "")
            date    = headers.get("date", "")

            attachments = _find_pdf_attachments(msg.get("payload", {}))
            if not attachments:
                continue

            first = attachments[0]
            canonical_source = _classify_source(sender, subject) or source
            latest_by_source[canonical_source] = {
                "message_id": msg_meta["id"],
                "sender":     sender,
                "subject":    subject,
                "date":       date,
                "date_dt":    _parse_email_date(date),
                "source":     canonical_source,
                "attachments": attachments,
                "attachment_id": first.get("attachment_id"),
                "filename":   first.get("filename"),
                "size":       first.get("size", 0),
                "confidence": _score_cas_confidence(sender, subject),
            }
            logger.info(
                "Gmail scan: found %s email — '%s' from '%s' (%s)",
                canonical_source, subject[:50], sender[:40], date[:20],
            )

    # Return in preference order; unknown sources appended last.
    ordered: list[dict] = []
    for src in SOURCE_PRIORITY:
        if src in latest_by_source:
            ordered.append(latest_by_source[src])
    for src, email in latest_by_source.items():
        if src not in SOURCE_PRIORITY:
            ordered.append(email)

    logger.info(
        "Gmail scan complete: %d sources found (%s)",
        len(ordered), ", ".join(e["source"] for e in ordered),
    )
    return ordered


def _find_pdf_attachments(payload: dict) -> list:
    """Recursively find PDF attachments in email payload."""
    attachments = []

    if payload.get("filename") and payload["filename"].lower().endswith(".pdf"):
        attach_id = payload.get("body", {}).get("attachmentId")
        if attach_id:
            attachments.append({
                "filename": payload["filename"],
                "attachment_id": attach_id,
                "size": payload.get("body", {}).get("size", 0),
            })

    for part in payload.get("parts", []):
        attachments.extend(_find_pdf_attachments(part))

    return attachments


def download_attachment(service, message_id: str, attachment_id: str) -> bytes:
    """Download a specific email attachment as bytes."""
    attachment = service.users().messages().attachments().get(
        userId="me", messageId=message_id, id=attachment_id
    ).execute()

    data = attachment.get("data", "")
    return base64.urlsafe_b64decode(data)


def _score_cas_confidence(sender: str, subject: str) -> float:
    """Score how likely an email is a CAS statement (0.0 - 1.0)."""
    score = 0.0
    sender_lower = sender.lower()
    subject_lower = subject.lower()

    # Sender matching
    for s in CAS_SENDERS:
        if s in sender_lower:
            score += 0.4
            break

    # Subject matching
    for kw in CAS_SUBJECTS:
        if kw in subject_lower:
            score += 0.3
            break

    # Specific high-confidence patterns
    if "e-cas" in subject_lower or "ecas" in subject_lower:
        score += 0.2
    if "nsdl" in sender_lower or "cdsl" in sender_lower:
        score += 0.1

    return min(round(score, 2), 1.0)
