"""test_reporter — run the diagnostics tool after a fix and attach a test document
(with screenshots) to the work issue, then advance it to `testing_qa`.

Wraps the existing `python -m diagnostics run` tool (Playwright scenarios +
screenshot capture). Best-effort and OFF by default:

  * Enabled only when TEST_REPORTER_ENABLED is truthy (running a browser from the
    API host is heavy and environment-dependent).
  * Needs a SESSION_TOKEN (env or frontend-v5/.env.test) for the diagnostics tool
    to authenticate; without it the tool exits and we record that, non-fatally.
  * Screenshots are embedded as bounded data URIs so the Work dashboard can render
    them directly.

Never raises into the caller (it's invoked fire-and-forget from fix_agent).
"""
from __future__ import annotations

import asyncio
import base64
import json
import logging
import os
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from deps import db
from helpers import secrets as _secrets

logger = logging.getLogger(__name__)
_COLLECTION = "work_issues"

REPO_ROOT = Path(__file__).resolve().parents[2]   # /app
MAX_SHOTS = 6
MAX_SHOT_BYTES = 800_000


def _enabled() -> bool:
    """Explicit TEST_REPORTER_ENABLED wins; otherwise ON in staging, OFF in production
    (mirrors fix_agent so the fix→test chain runs end-to-end on staging)."""
    explicit = os.environ.get("TEST_REPORTER_ENABLED")
    if explicit not in (None, ""):
        return explicit.strip().lower() in ("1", "true", "yes", "on")
    return _secrets.current_env() != "production"


def _run_diagnostics_blocking(env: str, out_json: Path) -> tuple[int, str]:
    """Blocking subprocess call to the diagnostics CLI. Returns (rc, stderr_tail)."""
    cmd = [sys.executable, "-m", "diagnostics", "run", "--env", env, "--output", str(out_json)]
    tag = os.environ.get("TEST_REPORTER_TAG")
    if tag:
        cmd += ["--tag", tag]
    try:
        proc = subprocess.run(
            cmd, cwd=str(REPO_ROOT), capture_output=True, text=True, timeout=600
        )
        return proc.returncode, (proc.stderr or "")[-800:]
    except subprocess.TimeoutExpired:
        return 124, "diagnostics run timed out after 600s"
    except Exception as e:  # noqa: BLE001
        return 1, f"diagnostics invocation failed: {e}"


def _encode_screenshot(path_str: str) -> Optional[str]:
    """Read a screenshot file and return a bounded data URI, or None."""
    if not path_str:
        return None
    p = Path(path_str)
    if not p.is_absolute():
        p = REPO_ROOT / path_str
    try:
        if not p.is_file() or p.stat().st_size > MAX_SHOT_BYTES:
            return None
        data = p.read_bytes()
        return f"data:image/png;base64,{base64.b64encode(data).decode()}"
    except OSError:
        return None


def _build_document(report: dict, pr_url: Optional[str]) -> tuple[str, list[str]]:
    """Turn a DiagnosticReport dict into a markdown test document + screenshot URIs."""
    total = report.get("total", 0)
    passed = report.get("passed", 0)
    failed = report.get("failed", 0)
    verdict = "PASS" if failed == 0 and total > 0 else ("FAIL" if failed else "NO TESTS")
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        f"# Test report — {verdict}",
        f"_Generated by test_reporter · {now} · env={report.get('env')}_",
        "",
        f"- **Scenarios:** {total}  ·  **passed:** {passed}  ·  **failed:** {failed}",
    ]
    if pr_url:
        lines.append(f"- **Fix PR:** {pr_url}")
    lines += ["", "## Test cases", ""]

    shots: list[str] = []
    for sc in report.get("scenarios", []):
        mark = "✅" if sc.get("passed") else "❌"
        lines.append(f"- {mark} **{sc.get('name')}** — {sc.get('description', '')} "
                     f"({sc.get('duration_ms', 0):.0f}ms)")
        if sc.get("error"):
            lines.append(f"    - error: `{str(sc['error'])[:200]}`")
        for f in sc.get("findings", []):
            lines.append(f"    - finding [{f.get('severity')}]: {f.get('title')}")
        for cand in (sc.get("screenshot_path"), *[f.get("screenshot") for f in sc.get("findings", [])]):
            if cand and len(shots) < MAX_SHOTS:
                uri = _encode_screenshot(cand)
                if uri:
                    shots.append(uri)
    lines += ["", f"## Verdict: {verdict}", ""]
    return "\n".join(lines), shots


async def run_test_report(issue_id: str, *, pr_url: Optional[str] = None) -> None:
    """Run diagnostics for an issue and attach the resulting test document. Never raises."""
    try:
        if not _enabled():
            await db[_COLLECTION].update_one(
                {"issue_id": issue_id},
                {"$set": {"remediation.detail": "test reporter disabled (set TEST_REPORTER_ENABLED=true)",
                          "updated_at": datetime.now(timezone.utc)}},
            )
            return
        env = os.environ.get("TEST_REPORTER_ENV", "staging")
        with tempfile.TemporaryDirectory(prefix="test-report-") as tmp:
            out_json = Path(tmp) / "report.json"
            rc, stderr_tail = await asyncio.get_event_loop().run_in_executor(
                None, _run_diagnostics_blocking, env, out_json
            )
            if not out_json.is_file():
                # Tool couldn't produce a report (likely missing SESSION_TOKEN / Playwright).
                await db[_COLLECTION].update_one(
                    {"issue_id": issue_id},
                    {"$set": {"remediation.detail": f"test run produced no report (rc={rc}): {stderr_tail[:200]}",
                              "updated_at": datetime.now(timezone.utc)}},
                )
                return
            report = json.loads(out_json.read_text())

        doc_md, shots = _build_document(report, pr_url)
        passed = report.get("failed", 1) == 0 and report.get("total", 0) > 0
        now = datetime.now(timezone.utc)
        update: dict = {
            "test_document": doc_md,
            "screenshots": shots,
            "updated_at": now,
        }
        # Fix passed its tests → move to Testing/QA for human sign-off.
        if passed:
            update["status"] = "testing_qa"
        await db[_COLLECTION].update_one(
            {"issue_id": issue_id},
            {"$set": update,
             "$push": {"comments": {"author": "test_reporter",
                                    "body": f"Attached test report ({'PASS' if passed else 'FAIL'}), "
                                            f"{len(shots)} screenshot(s).",
                                    "created_at": now.isoformat()}}},
        )
        logger.info("test_reporter %s → %s (%d shots)", issue_id, "PASS" if passed else "FAIL", len(shots))
    except Exception as e:  # noqa: BLE001
        logger.warning("test_reporter %s failed: %s", issue_id, e)
