import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardLabel } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { MetricCard } from "@/components/shared/MetricCard";
import { CapBar } from "@/components/charts/CapBar";
import { formatINR, formatPct } from "@/lib/formatters";
export function Risk({ data }) {
    return (_jsxs("div", { className: "px-6 py-8 lg:px-10 lg:py-10 max-w-[1080px] mx-auto w-full", children: [_jsxs("div", { className: "flex items-start gap-4", children: [_jsxs("div", { children: [_jsx("div", { className: "font-mono text-[11px] uppercase tracking-[.18em] text-ink-3", children: "Risk analysis" }), _jsxs("h1", { className: "font-display text-3xl sm:text-4xl tracking-tightish leading-[1.05] mt-1.5", children: ["One bad quarter could cost ", _jsx("span", { className: "text-warm", children: formatINR(data.vaR95Paise, { compact: true }) }), "."] }), _jsx("p", { className: "text-[15.5px] text-ink-2 mt-3 max-w-[600px] leading-relaxed", children: "That's the 95th-percentile worst case over 12 months \u2014 a 1-in-20 scenario. Likely milder, useful to know." })] }), _jsx(Badge, { tone: "warm", className: "ml-auto shrink-0", children: "ATTENTION" })] }), _jsxs("div", { className: "grid grid-cols-2 lg:grid-cols-4 gap-3 mt-7", children: [_jsx(MetricCard, { label: "VaR \u00B7 95th \u00B7 1Y", value: formatPct(-data.vaR95Pct, { signed: true }), subtext: `~${formatINR(data.vaR95Paise, { compact: true })}`, tone: "warm" }), _jsx(MetricCard, { label: "Volatility", value: formatPct(data.annualVolPct), subtext: `Bench ${formatPct(data.benchmarkVolPct)}` }), _jsx(MetricCard, { label: "Max drawdown", value: formatPct(data.maxDrawdownPct), subtext: "historical worst", tone: "accent" }), _jsx(MetricCard, { label: "Beta", value: data.beta.toFixed(2), subtext: "vs NIFTY 500" })] }), _jsxs(Card, { className: "mt-5 p-6", children: [_jsx(CardLabel, { children: "What's making it risky \u00B7 share of \u03C3" }), _jsx("ul", { className: "mt-4 flex flex-col gap-3", children: data.riskDrivers.map((d) => (_jsxs("li", { className: "grid grid-cols-[1fr_240px_60px] gap-4 items-center", children: [_jsx("span", { className: "text-[14px]", children: d.name }), _jsx(CapBar, { pct: d.sharePct, height: 6 }), _jsxs("span", { className: "font-mono num text-[13px] text-right", children: [d.sharePct, "%"] })] }, d.name))) })] }), _jsxs(Card, { className: "mt-5 p-6", children: [_jsxs("div", { className: "flex items-center mb-4", children: [_jsx(CardLabel, { children: "Stress scenarios \u00B7 simulated impact" }), _jsx("span", { className: "ml-auto text-[12px] text-ink-3", children: "5 scenarios" })] }), _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { children: _jsx("tr", { className: "border-b border-hairline", children: ["Scenario", "Portfolio", "Benchmark", "Recovery"].map((h) => (_jsx("th", { className: "text-left font-mono text-[10px] uppercase tracking-[.12em] text-ink-3 font-normal px-3 py-2", children: h }, h))) }) }), _jsx("tbody", { children: data.stressScenarios.map((s) => {
                                    const tone = s.portfolioPct < -0.2 ? "text-neg" : s.portfolioPct < -0.05 ? "text-warm" : "text-pos";
                                    return (_jsxs("tr", { className: "border-t border-hairline", children: [_jsx("td", { className: "px-3 py-3 text-[14px] font-medium", children: s.name }), _jsx("td", { className: `px-3 py-3 font-mono num text-[13px] ${tone}`, children: formatPct(s.portfolioPct, { signed: true }) }), _jsx("td", { className: "px-3 py-3 font-mono num text-[12px] text-ink-3", children: formatPct(s.benchPct, { signed: true }) }), _jsx("td", { className: "px-3 py-3 text-[12px] text-ink-3", children: s.recovery })] }, s.name));
                                }) })] })] })] }));
}
