"""Persona-tagged Copilot prompt catalog — 99 entries across 10 investor personas.

Single source of truth for persona-specific starter prompts surfaced after CAS
upload and via the chat suggested-prompts panel. Imported by `copilot_prompts.py`
and merged into the `_PROMPT_TEMPLATES` list used by the scoring endpoint.

Each entry shape (matches the universal templates in `copilot_prompts.py`):
    id:                stable string id
    personas:          list of PersonaType.value strings — entry only shown to
                       users whose persona is in this list
    intent_category:   one of portfolio_health | performance | risk_diversification |
                       tax | goal_planning  (the 5 product taxonomy buckets)
    bucket:            legacy UI bucket (kept for compatibility)
    tier:              primary | secondary | advanced  (controls UI prominence)
    label:             user-facing chip text
    outcome:           1-line value proposition shown on card
    query:             full sentence sent to the copilot when chip is tapped
    icon:              lucide icon name
    color:             tailwind colour token
    scorer:            (ctx) -> (score:int, badge:str|None)

Catalog see-also: /app/docs/COPILOT_PROMPT_CATALOG.md
"""
from __future__ import annotations

from typing import Any, Dict, List, Tuple


# ─────────────────────────────────────────────────────────────────────────
# Tier-based scorers — persona templates use a base score gated on the user
# having any holdings. Persona-filtering happens at the endpoint level.
# ─────────────────────────────────────────────────────────────────────────

def _scorer_primary(ctx: Dict[str, Any]) -> Tuple[int, None]:
    return (90 if (ctx.get("total_value", 0) or 0) > 0 else 0, None)


def _scorer_secondary(ctx: Dict[str, Any]) -> Tuple[int, None]:
    return (55 if (ctx.get("total_value", 0) or 0) > 0 else 0, None)


def _scorer_advanced(ctx: Dict[str, Any]) -> Tuple[int, None]:
    return (30 if (ctx.get("total_value", 0) or 0) > 0 else 0, None)


# General-question scorers (educator-routed, don't need holdings)
def _scorer_advanced_universal(_ctx: Dict[str, Any]) -> Tuple[int, None]:
    return (28, None)


_TIER_SCORERS = {
    "primary":   _scorer_primary,
    "secondary": _scorer_secondary,
    "advanced":  _scorer_advanced,
}


def _entry(
    eid: str,
    persona: str,
    category: str,
    tier: str,
    label: str,
    outcome: str,
    query: str,
    icon: str,
    color: str,
    *,
    holdings_required: bool = True,
) -> Dict[str, Any]:
    """Compact constructor — keeps the catalog readable."""
    scorer = _TIER_SCORERS[tier] if holdings_required else _scorer_advanced_universal
    return {
        "id": eid,
        "personas": [persona],
        "intent_category": category,
        "bucket": f"persona_{persona}",
        "tier": tier,
        "label": label,
        "outcome": outcome,
        "query": query,
        "icon": icon,
        "color": color,
        "scorer": scorer,
    }


# Persona codes (PersonaType.value)
_BEGINNER = "beginner_investor"
_MF       = "mutual_fund_investor"
_EQUITY   = "stock_investor"
_HNI      = "hni_investor"
_RETIRE   = "retirement_planner"
_PARENTS  = "parents_planning"
_TAX      = "tax_saver"
_CONS     = "conservative_investor"
_TRADER   = "active_trader"
_NRI      = "nri_investor"


PERSONA_TEMPLATES: List[Dict[str, Any]] = [
    # ─── 1. Salaried Beginner Investor ──────────────────────────────────
    _entry("beg_diversified", _BEGINNER, "risk_diversification", "primary",
           "Is my portfolio well diversified?",
           "Check spread across stocks, funds and asset types",
           "Is my portfolio well diversified across asset classes, sectors and individual holdings? Explain in simple terms.",
           "Compass", "sky"),
    _entry("beg_too_much_risk", _BEGINNER, "risk_diversification", "secondary",
           "Am I taking too much risk?",
           "See if your risk level matches your profile",
           "Am I taking too much risk for someone like me? Compare my portfolio risk to my risk profile.",
           "Shield", "amber"),
    _entry("beg_weak_funds", _BEGINNER, "performance", "secondary",
           "Which mutual funds are underperforming?",
           "Spot funds lagging their benchmark",
           "Which of my mutual funds are underperforming their benchmarks? Should I switch them?",
           "TrendingDown", "rose"),
    _entry("beg_should_sell", _BEGINNER, "portfolio_health", "secondary",
           "Should I sell any of my stocks or funds?",
           "Tax-smart exit suggestions",
           "Should I sell any of my stocks or funds right now? Be specific and include tax impact.",
           "ArrowRightCircle", "amber"),
    _entry("beg_vs_fd", _BEGINNER, "performance", "advanced",
           "How much return vs FD?",
           "Compare your returns to a fixed deposit",
           "How much return am I generating compared to a fixed deposit? Show the gap clearly.",
           "BarChart3", "emerald"),
    _entry("beg_how_much_sip", _BEGINNER, "goal_planning", "secondary",
           "How much should I invest every month?",
           "Right SIP for your income and goals",
           "How much should I invest every month given my income and long-term goals?",
           "Coins", "indigo",
           holdings_required=False),
    _entry("beg_best_funds_long", _BEGINNER, "portfolio_health", "advanced",
           "Best mutual funds for long-term wealth?",
           "Curated long-horizon fund picks",
           "Which mutual funds are best for long-term wealth creation? Give me 3 concrete picks.",
           "Sparkles", "violet",
           holdings_required=False),
    _entry("beg_stocks_or_mf", _BEGINNER, "goal_planning", "advanced",
           "Stocks or mutual funds?",
           "Pick the right vehicle for you",
           "Should I invest in stocks or mutual funds? Explain the trade-off for a beginner.",
           "BookOpen", "slate",
           holdings_required=False),
    _entry("beg_80c", _BEGINNER, "tax", "advanced",
           "How do I save tax under 80C?",
           "Section 80C options ranked by suitability",
           "How do I save tax under Section 80C? What are the best options?",
           "Receipt", "yellow",
           holdings_required=False),
    _entry("beg_retirement_corpus", _BEGINNER, "goal_planning", "advanced",
           "How much corpus for retirement?",
           "Required nest egg for your age",
           "How much corpus will I need for retirement? Walk me through the math.",
           "Target", "teal",
           holdings_required=False),

    # ─── 2. Mutual Fund Focused Investor ────────────────────────────────
    _entry("mf_too_many", _MF, "portfolio_health", "primary",
           "Do I have too many mutual funds?",
           "Right-size your fund count for your portfolio",
           "Do I have too many mutual funds? What is the ideal number for my portfolio size?",
           "Layers", "indigo"),
    _entry("mf_overlap_deep", _MF, "risk_diversification", "secondary",
           "Are my funds overlapping significantly?",
           "Pairwise fund overlap analysis",
           "Which of my mutual funds are overlapping significantly? Show the top 3 overlapping pairs.",
           "Layers", "purple"),
    _entry("mf_drag", _MF, "performance", "secondary",
           "Which funds are dragging performance?",
           "Identify the laggards in your portfolio",
           "Which of my funds are dragging down my overall portfolio performance? Suggest replacements.",
           "TrendingDown", "rose"),
    _entry("mf_sip_optimal", _MF, "goal_planning", "secondary",
           "Is my SIP allocation optimal?",
           "Distribute SIP across categories better",
           "Is my SIP allocation optimal across my chosen funds? Should I rebalance the SIP amounts?",
           "Coins", "emerald"),
    _entry("mf_direct_plans", _MF, "tax", "advanced",
           "Should I switch to direct plans?",
           "Compute the savings from regular → direct",
           "Should I switch to direct plans? How much would I save annually on expense ratio?",
           "Sparkles", "amber"),
    _entry("mf_best_sip_funds", _MF, "portfolio_health", "secondary",
           "Best funds for SIP?",
           "Top SIP picks by category",
           "Which funds are best for SIP right now in each major category?",
           "Sparkles", "emerald",
           holdings_required=False),
    _entry("mf_categories_explained", _MF, "risk_diversification", "advanced",
           "Large-cap vs flexi-cap vs mid-cap?",
           "Category trade-offs explained",
           "Explain the difference between large-cap, flexi-cap, and mid-cap mutual funds and which suits me.",
           "BookOpen", "slate",
           holdings_required=False),
    _entry("mf_equity_for_age", _MF, "risk_diversification", "advanced",
           "How much equity for my age?",
           "Age-appropriate equity allocation",
           "How much equity allocation is suitable for my age? Use a proven thumb rule.",
           "Scale", "sky",
           holdings_required=False),
    _entry("mf_sip_in_correction", _MF, "goal_planning", "advanced",
           "SIP during market correction?",
           "Whether to continue SIP when markets fall",
           "Should I continue investing through SIP during market corrections? Back it with data.",
           "Activity", "violet",
           holdings_required=False),
    _entry("mf_expense_ratio_impact", _MF, "performance", "advanced",
           "How do expense ratios affect returns?",
           "The long-term drag from high TER",
           "How do expense ratios affect long-term returns? Show me the 20-year impact.",
           "Receipt", "yellow",
           holdings_required=False),

    # ─── 3. Direct Equity Investor ──────────────────────────────────────
    _entry("eq_overvalued", _EQUITY, "performance", "primary",
           "Which stocks are overvalued?",
           "Spot the priciest names in your portfolio",
           "Which of my stocks look overvalued on P/E and P/B today? Should I trim them?",
           "TrendingUp", "rose"),
    _entry("eq_weak_fundamentals", _EQUITY, "portfolio_health", "secondary",
           "Which stocks have weak fundamentals?",
           "ROE, debt, earnings quality flags",
           "Which of my stocks have weak fundamentals (ROE, debt, earnings)? Walk me through each.",
           "AlertTriangle", "amber"),
    _entry("eq_concentration", _EQUITY, "risk_diversification", "secondary",
           "What is my concentration risk?",
           "Sector and company-level concentration",
           "What is the concentration risk in my equity portfolio? Show sector and single-stock exposure.",
           "AlertTriangle", "red"),
    _entry("eq_top_contributors", _EQUITY, "performance", "secondary",
           "Which stocks contribute most to returns?",
           "Your winners and losers ranked",
           "Which of my stocks have contributed most to my returns? Rank them by P&L.",
           "BarChart3", "emerald"),
    _entry("eq_rebalance", _EQUITY, "portfolio_health", "advanced",
           "Should I rebalance my holdings?",
           "Trim winners, add to laggards",
           "Should I rebalance my equity holdings now? Suggest specific buy / sell amounts.",
           "Scale", "indigo"),
    _entry("eq_sector_outperform", _EQUITY, "performance", "secondary",
           "Which sectors will outperform?",
           "Sector rotation signal today",
           "Which Indian sectors are likely to outperform over the next 12 months and why?",
           "TrendingUp", "violet",
           holdings_required=False),
    _entry("eq_find_undervalued", _EQUITY, "risk_diversification", "advanced",
           "How do I identify undervalued stocks?",
           "Framework for finding hidden gems",
           "How do I identify undervalued stocks? Give me a step-by-step framework.",
           "BookOpen", "slate",
           holdings_required=False),
    _entry("eq_key_metrics", _EQUITY, "performance", "advanced",
           "Which valuation metrics matter most?",
           "P/E, P/B, ROE, EPS — which to trust",
           "Which valuation metrics matter most for stock picking and why?",
           "BookOpen", "teal",
           holdings_required=False),
    _entry("eq_long_term_portfolio", _EQUITY, "goal_planning", "advanced",
           "How to build a long-term stock portfolio?",
           "Construction principles for 10+ year holds",
           "How do I build a stock portfolio for a 10-year-plus horizon? What rules should I follow?",
           "Target", "indigo",
           holdings_required=False),
    _entry("eq_how_much_cash", _EQUITY, "risk_diversification", "advanced",
           "How much cash should I keep?",
           "Optimal cash buffer for opportunities",
           "How much cash should I keep in my portfolio? What is the right buffer for new opportunities?",
           "Coins", "sky",
           holdings_required=False),

    # ─── 4. HNI Investor ────────────────────────────────────────────────
    _entry("hni_wealth_alloc", _HNI, "risk_diversification", "primary",
           "Is my wealth allocation optimal?",
           "Multi-asset view: equity / debt / gold / international",
           "Is my wealth allocation optimal across asset classes? Compare to an HNI-grade benchmark mix.",
           "Briefcase", "indigo"),
    _entry("hni_highest_concentration", _HNI, "risk_diversification", "secondary",
           "Where is concentration risk highest?",
           "AMC / sector / single-stock hotspots",
           "Where is concentration risk highest in my portfolio — by AMC, sector, or individual position?",
           "AlertTriangle", "red"),
    _entry("hni_tax_efficiency", _HNI, "tax", "secondary",
           "How tax-efficient is my portfolio?",
           "STCG / LTCG drag and optimisation room",
           "How tax-efficient is my portfolio? Show STCG / LTCG drag and where I can improve.",
           "Receipt", "amber"),
    _entry("hni_rebalance_assets", _HNI, "portfolio_health", "secondary",
           "Which assets to rebalance?",
           "Cross-asset deviation from target",
           "Which assets in my portfolio should be rebalanced? Show deviation from my target allocation.",
           "Scale", "emerald"),
    _entry("hni_downside_crash", _HNI, "risk_diversification", "advanced",
           "Portfolio downside in a market crash?",
           "Stress-test against 20-30% drawdown",
           "What is my portfolio's downside if equity markets fall 25%? Show rupee impact and recovery time.",
           "Activity", "rose"),
    _entry("hni_global_allocation", _HNI, "risk_diversification", "secondary",
           "Allocation across equity, debt, gold, international?",
           "Benchmark multi-asset mix for HNIs",
           "How should I allocate across equity, debt, gold and international assets at my net worth?",
           "Globe", "sky",
           holdings_required=False),
    _entry("hni_tax_strategies", _HNI, "tax", "advanced",
           "Best tax-saving strategies?",
           "HNI-grade tax planning playbook",
           "What are the best tax-saving strategies for HNIs in India? Cover capital gains, dividend and rental.",
           "Lightbulb", "yellow",
           holdings_required=False),
    _entry("hni_pms_aif", _HNI, "portfolio_health", "advanced",
           "Should I use PMS or AIFs?",
           "When alternatives beat mutual funds",
           "Should I use PMS or AIFs at my level? Compare costs, taxation and access vs mutual funds.",
           "Building", "violet",
           holdings_required=False),
    _entry("hni_wealth_generations", _HNI, "goal_planning", "advanced",
           "How to preserve wealth across generations?",
           "Multi-generational wealth playbook",
           "How can I preserve and grow wealth across generations? What structures matter most?",
           "Heart", "teal",
           holdings_required=False),
    _entry("hni_estate_planning", _HNI, "goal_planning", "advanced",
           "How to structure estate planning?",
           "Wills, trusts, nomination strategy",
           "How should I structure my estate planning — wills, trusts, nominations? Walk me through it.",
           "Building", "slate",
           holdings_required=False),

    # ─── 5. Retirement Planner ──────────────────────────────────────────
    _entry("ret_sufficient", _RETIRE, "goal_planning", "primary",
           "Will my investments cover retirement?",
           "Sufficiency check with Monte-Carlo confidence",
           "Will my current investments be sufficient for retirement? Show the probability of success.",
           "Target", "indigo"),
    _entry("ret_debt_adequate", _RETIRE, "risk_diversification", "secondary",
           "Is my debt allocation adequate?",
           "Debt share for a retiree-grade portfolio",
           "Is my debt allocation adequate for someone close to retirement? Compare to recommended share.",
           "Shield", "sky"),
    _entry("ret_monthly_income", _RETIRE, "goal_planning", "secondary",
           "How much monthly income can this generate?",
           "Sustainable withdrawal at safe rate",
           "How much monthly income can my current portfolio generate sustainably using a safe withdrawal rate?",
           "Coins", "emerald"),
    _entry("ret_running_out", _RETIRE, "goal_planning", "secondary",
           "Probability of running out of money?",
           "Monte-Carlo failure probability",
           "What is the probability that I will run out of money in retirement? Show worst-case corpus path.",
           "Activity", "rose"),
    _entry("ret_shift_safer", _RETIRE, "portfolio_health", "advanced",
           "Which assets to shift to safer investments?",
           "De-risk path to retirement",
           "Which of my assets should I shift to safer investments as I approach retirement? Be specific.",
           "Scale", "amber"),
    _entry("ret_required_corpus", _RETIRE, "goal_planning", "secondary",
           "How much corpus do I need?",
           "Inflation-adjusted retirement corpus",
           "How much corpus do I need for retirement to maintain my current lifestyle, adjusted for inflation?",
           "Target", "teal",
           holdings_required=False),
    _entry("ret_retirees_invest", _RETIRE, "risk_diversification", "advanced",
           "How should retirees invest?",
           "Allocation playbook for retirees",
           "How should retirees invest their corpus? Cover allocation, income and capital preservation.",
           "BookOpen", "slate",
           holdings_required=False),
    _entry("ret_withdrawal_rate", _RETIRE, "goal_planning", "advanced",
           "What withdrawal rate is safe?",
           "4% rule and Indian variants",
           "What withdrawal rate is safe in India? Discuss the 4% rule and Indian-context adjustments.",
           "Lightbulb", "yellow",
           holdings_required=False),
    _entry("ret_inflation", _RETIRE, "goal_planning", "advanced",
           "How to protect against inflation?",
           "Inflation-beating asset choices",
           "How do I protect my retirement corpus against inflation? What assets actually beat inflation?",
           "Sparkles", "violet",
           holdings_required=False),
    _entry("ret_annuities", _RETIRE, "goal_planning", "advanced",
           "Should I invest in annuities?",
           "Annuity vs SWP trade-offs",
           "Should I invest in annuities for retirement income? Compare to SWP from mutual funds.",
           "Briefcase", "indigo",
           holdings_required=False),

    # ─── 6. Parents Planning for Children ──────────────────────────────
    _entry("par_edu_on_track", _PARENTS, "goal_planning", "primary",
           "Is my child education corpus on track?",
           "Goal-progress against the target",
           "Is my child education corpus on track? Show progress, shortfall and time-to-goal.",
           "GraduationCap", "indigo"),
    _entry("par_sip_sufficient", _PARENTS, "goal_planning", "secondary",
           "Are current SIPs sufficient?",
           "Required vs actual monthly investment",
           "Are my current SIPs sufficient to fund my child's education goal? Show the gap.",
           "Coins", "emerald"),
    _entry("par_return_assumptions", _PARENTS, "goal_planning", "secondary",
           "What return assumptions are realistic?",
           "Base / bull / bear scenarios for the goal",
           "What return assumptions are realistic for my child education goal? Show base, bull and bear scenarios.",
           "Activity", "sky"),
    _entry("par_shortfall", _PARENTS, "goal_planning", "secondary",
           "How much shortfall exists?",
           "Gap between projected corpus and target",
           "How much shortfall exists between my projected corpus and the education target?",
           "TrendingDown", "rose"),
    _entry("par_earmarked", _PARENTS, "portfolio_health", "advanced",
           "Which investments are earmarked for education?",
           "Goal-asset mapping",
           "Which of my investments are earmarked for the education goal? Should any be added or moved?",
           "Briefcase", "amber"),
    _entry("par_cost_higher_ed", _PARENTS, "goal_planning", "secondary",
           "How much will higher education cost?",
           "Inflation-adjusted education cost",
           "How much will higher education cost in 10-15 years for an Indian student going abroad vs in India?",
           "GraduationCap", "violet",
           holdings_required=False),
    _entry("par_monthly_invest", _PARENTS, "goal_planning", "secondary",
           "How much to invest monthly?",
           "SIP needed to hit the goal",
           "How much should I invest every month to fund my child's education comfortably?",
           "Coins", "emerald",
           holdings_required=False),
    _entry("par_equity_for_edu", _PARENTS, "goal_planning", "advanced",
           "Equity funds for education planning?",
           "Risk-return fit for the horizon",
           "Should I use equity mutual funds for my child education goal? What allocation is appropriate?",
           "Scale", "teal",
           holdings_required=False),
    _entry("par_short_horizon", _PARENTS, "goal_planning", "advanced",
           "Goal only 5 years away — what now?",
           "Shortened horizon → safer assets",
           "My education goal is only 5 years away. How should I shift allocation now?",
           "AlertTriangle", "amber",
           holdings_required=False),
    _entry("par_insurance_overlay", _PARENTS, "goal_planning", "advanced",
           "Protect the goal with insurance?",
           "Term insurance to safeguard the goal",
           "How do I protect my child's education goal with insurance in case something happens to me?",
           "Shield", "sky",
           holdings_required=False),

    # ─── 7. Tax-Conscious Investor ──────────────────────────────────────
    _entry("tax_unrealized", _TAX, "tax", "primary",
           "What are my unrealized capital gains?",
           "STCG / LTCG sitting in your portfolio",
           "What are my unrealized capital gains right now? Break down by STCG vs LTCG and asset type.",
           "Receipt", "yellow"),
    _entry("tax_harvest_candidates", _TAX, "tax", "secondary",
           "Which holdings can I sell for tax harvesting?",
           "Loss-harvest candidates ranked",
           "Which holdings should I consider selling for tax-loss harvesting this year?",
           "Sparkles", "emerald"),
    _entry("tax_inefficient_assets", _TAX, "tax", "secondary",
           "Which assets generate tax inefficiency?",
           "High-tax-drag holdings",
           "Which of my assets are tax-inefficient? Where is the biggest tax drag in my portfolio?",
           "TrendingDown", "rose"),
    _entry("tax_rebalance_cost", _TAX, "tax", "secondary",
           "Tax cost if I rebalance now?",
           "Pre-trade tax estimate",
           "How much tax will I pay if I rebalance my portfolio today? Show STCG / LTCG breakdown.",
           "Scale", "amber"),
    _entry("tax_fy_end_timing", _TAX, "tax", "advanced",
           "Hold or sell before FY ends?",
           "LTCG flip and exemption timing",
           "Should I hold or sell some positions before the financial year ends? Use the ₹1.25L LTCG exemption.",
           "Activity", "violet"),
    _entry("tax_cap_gains_basics", _TAX, "tax", "secondary",
           "How does capital gains tax work?",
           "STCG / LTCG / surcharge explained",
           "Explain how capital gains tax works for equity, debt and gold in India.",
           "BookOpen", "slate",
           holdings_required=False),
    _entry("tax_loss_harvest_concept", _TAX, "tax", "advanced",
           "What is tax-loss harvesting?",
           "The concept with an Indian example",
           "Explain tax-loss harvesting with an Indian example and the wash-sale considerations.",
           "BookOpen", "indigo",
           holdings_required=False),
    _entry("tax_efficient_picks", _TAX, "tax", "advanced",
           "Which investments are most tax-efficient?",
           "Tax-efficient instrument ranking",
           "Which investment instruments are most tax-efficient in India? Rank them.",
           "Lightbulb", "emerald",
           holdings_required=False),
    _entry("tax_growth_vs_idcw", _TAX, "tax", "advanced",
           "Growth or IDCW plan?",
           "Tax outcome of each option",
           "Should I choose growth or IDCW plan for my mutual funds? Compare the tax outcomes.",
           "Scale", "amber",
           holdings_required=False),
    _entry("tax_minimise_legally", _TAX, "tax", "advanced",
           "How to minimise taxes legally?",
           "Top legal tax-saving moves",
           "What are the top ways to minimise my taxes legally in India? Cover both deductions and structuring.",
           "Sparkles", "yellow",
           holdings_required=False),

    # ─── 8. Conservative Investor ───────────────────────────────────────
    _entry("cons_too_aggressive", _CONS, "risk_diversification", "primary",
           "Is my portfolio too aggressive?",
           "Risk vs your conservative profile",
           "Is my portfolio too aggressive for my conservative risk profile? Show the mismatch.",
           "AlertTriangle", "rose"),
    _entry("cons_downside", _CONS, "risk_diversification", "secondary",
           "How much downside do I face?",
           "Max drawdown estimate",
           "How much downside risk do I face in a bad market? Estimate my max drawdown.",
           "Activity", "amber"),
    _entry("cons_debt_share", _CONS, "risk_diversification", "secondary",
           "How much is in debt / fixed income?",
           "Debt allocation today",
           "How much of my portfolio is allocated to debt and fixed-income instruments?",
           "Shield", "sky"),
    _entry("cons_volatile_holdings", _CONS, "risk_diversification", "secondary",
           "Which holdings are most volatile?",
           "Volatility ranking of holdings",
           "Which of my holdings are most volatile? Rank them so I can trim the risky names.",
           "BarChart3", "violet"),
    _entry("cons_beat_fd", _CONS, "performance", "advanced",
           "Can I beat FD with low risk?",
           "Low-risk return ideas vs FD",
           "Can I earn better returns than a fixed deposit with similar low risk? Suggest options.",
           "TrendingUp", "emerald"),
    _entry("cons_safe_options", _CONS, "risk_diversification", "secondary",
           "What are safe investment options?",
           "Low-risk instruments ranked",
           "What are the safest investment options available in India today and their typical returns?",
           "Shield", "sky",
           holdings_required=False),
    _entry("cons_debt_funds", _CONS, "portfolio_health", "advanced",
           "Which debt funds are suitable?",
           "Curated debt fund picks",
           "Which debt mutual funds are most suitable for a conservative investor like me?",
           "Layers", "indigo",
           holdings_required=False),
    _entry("cons_equity_share", _CONS, "risk_diversification", "advanced",
           "How much equity should I own?",
           "Equity share for a conservative profile",
           "How much equity should I own as a conservative investor at my age?",
           "Scale", "amber",
           holdings_required=False),
    _entry("cons_gold_hedge", _CONS, "risk_diversification", "advanced",
           "Is gold a safe hedge?",
           "Role of gold for capital preservation",
           "Is gold a safe hedge for a conservative portfolio? How much should I allocate?",
           "Sun", "yellow",
           holdings_required=False),
    _entry("cons_preserve_capital", _CONS, "goal_planning", "advanced",
           "How to preserve capital?",
           "Capital preservation playbook",
           "How do I preserve my capital while still beating inflation? Walk me through the trade-off.",
           "Heart", "teal",
           holdings_required=False),

    # ─── 9. Active Trader (Q5 win-rate hidden until P3) ─────────────────
    _entry("tra_best_positions", _TRADER, "performance", "primary",
           "Which positions are doing best?",
           "Winners ranked by P&L",
           "Which of my positions are generating the best returns right now? Rank them.",
           "TrendingUp", "emerald"),
    _entry("tra_overexposed", _TRADER, "risk_diversification", "secondary",
           "Where am I overexposed?",
           "Concentration in sectors and names",
           "Where am I overexposed across sectors and individual names? Highlight the top three risks.",
           "AlertTriangle", "red"),
    _entry("tra_pnl_split", _TRADER, "performance", "secondary",
           "What is my realized vs unrealized P&L?",
           "Realised vs sitting gains breakdown",
           "What is my realised vs unrealised profit and loss across positions?",
           "BarChart3", "violet"),
    _entry("tra_losing_trades", _TRADER, "performance", "secondary",
           "Which trades are consistently losing?",
           "Loss-makers ranked by drag",
           "Which of my trades are consistently losing? Rank them by total drag on the portfolio.",
           "TrendingDown", "rose"),
    # NOTE: trader Q5 (win ratio / risk-reward) intentionally hidden until P3 ships the underlying primitive.
    _entry("tra_sectors_momentum", _TRADER, "performance", "secondary",
           "Which sectors show momentum?",
           "Top-momentum sectors today",
           "Which Indian sectors are showing the strongest momentum today and over the last 30 days?",
           "TrendingUp", "indigo",
           holdings_required=False),
    _entry("tra_swing_setup", _TRADER, "performance", "advanced",
           "Effective swing trading setup?",
           "Repeatable swing entry rules",
           "What is an effective swing trading setup? Give me the entry, stop and exit rules.",
           "BookOpen", "slate",
           holdings_required=False),
    _entry("tra_risk_management", _TRADER, "risk_diversification", "advanced",
           "How do I manage risk?",
           "Risk-per-trade discipline",
           "How do I manage risk as an active trader? Cover position sizing and stop discipline.",
           "Shield", "amber",
           holdings_required=False),
    _entry("tra_position_size", _TRADER, "risk_diversification", "advanced",
           "What position size should I use?",
           "Sizing rule per trade",
           "What position size should I use per trade given my capital and risk tolerance?",
           "Scale", "sky",
           holdings_required=False),
    _entry("tra_discipline", _TRADER, "performance", "advanced",
           "How to improve trading discipline?",
           "Habits that compound trader edge",
           "How do I improve my trading discipline? Give me actionable daily habits.",
           "Heart", "teal",
           holdings_required=False),

    # ─── 10. NRI / Global Investor ──────────────────────────────────────
    _entry("nri_india_focus", _NRI, "risk_diversification", "primary",
           "How much is India-focused?",
           "India vs global share of portfolio",
           "What share of my portfolio is India-focused vs global? Show INR vs foreign currency exposure.",
           "Globe", "indigo"),
    _entry("nri_global_diversification", _NRI, "risk_diversification", "secondary",
           "Do I have global diversification?",
           "International exposure check",
           "Do I have adequate global diversification? Compare my international share to a recommended target.",
           "Compass", "sky"),
    _entry("nri_currency_risk", _NRI, "risk_diversification", "secondary",
           "What are my currency risks?",
           "INR-vs-USD/AED/SGD exposure",
           "What currency risks do I have? Break down INR vs other currencies and the impact of a 10% INR drop.",
           "Activity", "amber"),
    _entry("nri_tax_inefficient", _NRI, "tax", "secondary",
           "Which holdings are tax-inefficient for an NRI?",
           "NRI-specific tax red flags",
           "Which of my holdings are tax-inefficient for an NRI in my country of residence? Cover TDS and DTAA.",
           "Receipt", "rose"),
    _entry("nri_geo_rebalance", _NRI, "portfolio_health", "advanced",
           "Rebalance between geographies?",
           "India vs global rebalance plan",
           "Should I rebalance between Indian and global investments now? Show a concrete plan.",
           "Scale", "violet"),
    _entry("nri_india_or_abroad", _NRI, "performance", "secondary",
           "Invest in India or abroad?",
           "Where to deploy fresh money",
           "Should I invest fresh money in India or abroad given current valuations and currency outlook?",
           "Globe", "emerald",
           holdings_required=False),
    _entry("nri_tax_treaties", _NRI, "tax", "advanced",
           "How do tax treaties work?",
           "DTAA basics for NRIs",
           "How do tax treaties (DTAA) work for NRIs investing in India? Walk me through a US-India example.",
           "BookOpen", "slate",
           holdings_required=False),
    _entry("nri_intl_etfs", _NRI, "portfolio_health", "advanced",
           "Which international ETFs are suitable?",
           "Curated global ETF picks",
           "Which international ETFs are suitable for an NRI investor? Suggest specific picks across US, EM and global.",
           "Sparkles", "indigo",
           holdings_required=False),
    _entry("nri_currency_impact", _NRI, "performance", "advanced",
           "How do currency movements affect returns?",
           "FX impact on global portfolios",
           "How do currency movements affect my returns when I invest in INR vs foreign assets?",
           "Activity", "amber",
           holdings_required=False),
    _entry("nri_global_allocation", _NRI, "risk_diversification", "advanced",
           "Best allocation for global diversification?",
           "Suggested India / US / EM / other mix",
           "What is the best allocation for global diversification at my risk profile? Cover India, US, EM and bonds.",
           "Compass", "sky",
           holdings_required=False),
]
