INDIAN_INSTRUMENTS = [
    {"name":"Reliance Industries","ticker":"RELIANCE","type":"equity","sector":"Energy"},
    {"name":"Tata Consultancy Services","ticker":"TCS","type":"equity","sector":"IT"},
    {"name":"HDFC Bank","ticker":"HDFCBANK","type":"equity","sector":"Banking"},
    {"name":"Infosys","ticker":"INFY","type":"equity","sector":"IT"},
    {"name":"ICICI Bank","ticker":"ICICIBANK","type":"equity","sector":"Banking"},
    {"name":"Hindustan Unilever","ticker":"HINDUNILVR","type":"equity","sector":"FMCG"},
    {"name":"ITC","ticker":"ITC","type":"equity","sector":"FMCG"},
    {"name":"State Bank of India","ticker":"SBIN","type":"equity","sector":"Banking"},
    {"name":"Bharti Airtel","ticker":"BHARTIARTL","type":"equity","sector":"Telecom"},
    {"name":"Kotak Mahindra Bank","ticker":"KOTAKBANK","type":"equity","sector":"Banking"},
    {"name":"Larsen & Toubro","ticker":"LT","type":"equity","sector":"Infrastructure"},
    {"name":"Axis Bank","ticker":"AXISBANK","type":"equity","sector":"Banking"},
    {"name":"Asian Paints","ticker":"ASIANPAINT","type":"equity","sector":"Chemicals"},
    {"name":"Bajaj Finance","ticker":"BAJFINANCE","type":"equity","sector":"Financial Services"},
    {"name":"Maruti Suzuki","ticker":"MARUTI","type":"equity","sector":"Auto"},
    {"name":"Sun Pharma","ticker":"SUNPHARMA","type":"equity","sector":"Pharma"},
    {"name":"Titan Company","ticker":"TITAN","type":"equity","sector":"Consumer"},
    {"name":"Wipro","ticker":"WIPRO","type":"equity","sector":"IT"},
    {"name":"HCL Technologies","ticker":"HCLTECH","type":"equity","sector":"IT"},
    {"name":"Bajaj Finserv","ticker":"BAJAJFINSV","type":"equity","sector":"Financial Services"},
    {"name":"NTPC","ticker":"NTPC","type":"equity","sector":"Energy"},
    {"name":"Power Grid Corporation","ticker":"POWERGRID","type":"equity","sector":"Energy"},
    {"name":"Nestle India","ticker":"NESTLEIND","type":"equity","sector":"FMCG"},
    {"name":"Tata Motors","ticker":"TATAMOTORS","type":"equity","sector":"Auto"},
    {"name":"Tata Steel","ticker":"TATASTEEL","type":"equity","sector":"Metals"},
    {"name":"Adani Enterprises","ticker":"ADANIENT","type":"equity","sector":"Diversified"},
    {"name":"Adani Ports","ticker":"ADANIPORTS","type":"equity","sector":"Infrastructure"},
    {"name":"Tech Mahindra","ticker":"TECHM","type":"equity","sector":"IT"},
    {"name":"IndusInd Bank","ticker":"INDUSINDBK","type":"equity","sector":"Banking"},
    {"name":"Mahindra & Mahindra","ticker":"M&M","type":"equity","sector":"Auto"},
    {"name":"JSW Steel","ticker":"JSWSTEEL","type":"equity","sector":"Metals"},
    {"name":"Hindalco","ticker":"HINDALCO","type":"equity","sector":"Metals"},
    {"name":"Coal India","ticker":"COALINDIA","type":"equity","sector":"Mining"},
    {"name":"Cipla","ticker":"CIPLA","type":"equity","sector":"Pharma"},
    {"name":"Dr Reddys","ticker":"DRREDDY","type":"equity","sector":"Pharma"},
    {"name":"Divis Labs","ticker":"DIVISLAB","type":"equity","sector":"Pharma"},
    {"name":"Britannia Industries","ticker":"BRITANNIA","type":"equity","sector":"FMCG"},
    {"name":"Eicher Motors","ticker":"EICHERMOT","type":"equity","sector":"Auto"},
    {"name":"Hero MotoCorp","ticker":"HEROMOTOCO","type":"equity","sector":"Auto"},
    {"name":"UPL","ticker":"UPL","type":"equity","sector":"Chemicals"},
    {"name":"Grasim Industries","ticker":"GRASIM","type":"equity","sector":"Cement"},
    {"name":"UltraTech Cement","ticker":"ULTRACEMCO","type":"equity","sector":"Cement"},
    {"name":"Shree Cement","ticker":"SHREECEM","type":"equity","sector":"Cement"},
    {"name":"Pidilite Industries","ticker":"PIDILITIND","type":"equity","sector":"Chemicals"},
    {"name":"Havells India","ticker":"HAVELLS","type":"equity","sector":"Consumer"},
    {"name":"Godrej Consumer Products","ticker":"GODREJCP","type":"equity","sector":"FMCG"},
    {"name":"Dabur India","ticker":"DABUR","type":"equity","sector":"FMCG"},
    {"name":"Zomato","ticker":"ZOMATO","type":"equity","sector":"IT"},
    {"name":"Paytm (One97)","ticker":"PAYTM","type":"equity","sector":"IT"},
    {"name":"Nykaa (FSN E-Commerce)","ticker":"NYKAA","type":"equity","sector":"Consumer"},
    {"name":"Delhivery","ticker":"DELHIVERY","type":"equity","sector":"Logistics"},
    {"name":"IRCTC","ticker":"IRCTC","type":"equity","sector":"IT"},
    {"name":"Trent","ticker":"TRENT","type":"equity","sector":"Retail"},
    {"name":"Avenue Supermarts (DMart)","ticker":"DMART","type":"equity","sector":"Retail"},
    {"name":"Varun Beverages","ticker":"VBL","type":"equity","sector":"FMCG"},
    {"name":"Dixon Technologies","ticker":"DIXON","type":"equity","sector":"Electronics"},
    {"name":"Polycab India","ticker":"POLYCAB","type":"equity","sector":"Electronics"},
    {"name":"SBI Life Insurance","ticker":"SBILIFE","type":"equity","sector":"Insurance"},
    {"name":"HDFC Life Insurance","ticker":"HDFCLIFE","type":"equity","sector":"Insurance"},
    {"name":"ICICI Lombard","ticker":"ICICIGI","type":"equity","sector":"Insurance"},
    # Mutual Funds
    {"name":"Axis Bluechip Fund - Direct Growth","ticker":"INF846K01DP8","type":"mutual_fund","sector":"Large Cap"},
    {"name":"Axis Midcap Fund - Direct Growth","ticker":"INF846K01EW2","type":"mutual_fund","sector":"Mid Cap"},
    {"name":"Axis Small Cap Fund - Direct Growth","ticker":"INF846K01EY8","type":"mutual_fund","sector":"Small Cap"},
    {"name":"HDFC Flexi Cap Fund - Direct Growth","ticker":"INF179K01BE7","type":"mutual_fund","sector":"Flexi Cap"},
    {"name":"HDFC Mid Cap Opportunities Fund - Direct Growth","ticker":"INF179K01BD9","type":"mutual_fund","sector":"Mid Cap"},
    {"name":"HDFC Balanced Advantage Fund - Direct Growth","ticker":"INF179K01WA6","type":"mutual_fund","sector":"Balanced"},
    {"name":"HDFC Small Cap Fund - Direct Growth","ticker":"INF179KA1SA9","type":"mutual_fund","sector":"Small Cap"},
    {"name":"HDFC NIFTY50 Equal Weight Index Fund - Direct Growth","ticker":"INF179KC1BM8","type":"mutual_fund","sector":"Index"},
    {"name":"ICICI Prudential Bluechip Fund - Direct Growth","ticker":"INF109K01BM2","type":"mutual_fund","sector":"Large Cap"},
    {"name":"ICICI Prudential Banking & Financial Services Fund - Growth","ticker":"INF109K01BU5","type":"mutual_fund","sector":"Banking"},
    {"name":"ICICI Prudential Nifty Next 50 Index Fund - Direct Growth","ticker":"INF109K01BY7","type":"mutual_fund","sector":"Index"},
    {"name":"SBI Bluechip Fund - Direct Growth","ticker":"INF200K01RB7","type":"mutual_fund","sector":"Large Cap"},
    {"name":"SBI Small Cap Fund - Direct Growth","ticker":"INF200K01RQ5","type":"mutual_fund","sector":"Small Cap"},
    {"name":"SBI Contra Fund - Regular Growth","ticker":"INF200K01362","type":"mutual_fund","sector":"Contra"},
    {"name":"SBI Large & Midcap Fund - Direct Growth","ticker":"INF200K01VY6","type":"mutual_fund","sector":"Large & Mid Cap"},
    {"name":"SBI Nifty Index Fund - Direct Growth","ticker":"INF200K01UW2","type":"mutual_fund","sector":"Index"},
    {"name":"Kotak Flexicap Fund - Direct Growth","ticker":"INF174K01FP5","type":"mutual_fund","sector":"Flexi Cap"},
    {"name":"Kotak Emerging Equity Fund - Direct Growth","ticker":"INF174K01FQ3","type":"mutual_fund","sector":"Mid Cap"},
    {"name":"Kotak Small Cap Fund - Direct Growth","ticker":"INF174K01FK6","type":"mutual_fund","sector":"Small Cap"},
    {"name":"Mirae Asset Large Cap Fund - Direct Growth","ticker":"INF769K01101","type":"mutual_fund","sector":"Large Cap"},
    {"name":"Mirae Asset ELSS Tax Saver Fund - Direct Growth","ticker":"INF769K01DW2","type":"mutual_fund","sector":"ELSS"},
    {"name":"Parag Parikh Flexi Cap Fund - Direct Growth","ticker":"INF879O01027","type":"mutual_fund","sector":"Flexi Cap"},
    {"name":"Parag Parikh Flexi Cap Fund - Regular Growth","ticker":"INF879001019","type":"mutual_fund","sector":"Flexi Cap"},
    {"name":"Nippon India Small Cap Fund - Direct Growth","ticker":"INF204K01K15","type":"mutual_fund","sector":"Small Cap"},
    {"name":"Nippon India Small Cap Fund - Growth","ticker":"INF204K01HY3","type":"mutual_fund","sector":"Small Cap"},
    {"name":"Nippon India Large Cap Fund - Direct Growth","ticker":"INF204K01X13","type":"mutual_fund","sector":"Large Cap"},
    {"name":"Nippon India Multi Cap Fund - Growth","ticker":"INF204K01489","type":"mutual_fund","sector":"Multi Cap"},
    {"name":"Franklin India Flexi Cap Fund - Direct Growth","ticker":"INF090101FK3","type":"mutual_fund","sector":"Flexi Cap"},
    {"name":"UTI Nifty 50 Index Fund - Direct Growth","ticker":"INF789F01JN2","type":"mutual_fund","sector":"Index"},
    {"name":"UTI ELSS Tax Saver Fund - Direct Growth","ticker":"INF789F01LC8","type":"mutual_fund","sector":"ELSS"},
    {"name":"Quant Small Cap Fund - Direct Growth","ticker":"INF966L01AB8","type":"mutual_fund","sector":"Small Cap"},
    {"name":"Quant Multi Asset Allocation Fund - Direct Growth","ticker":"INF966L01218","type":"mutual_fund","sector":"Multi Asset"},
    {"name":"Tata Digital India Fund - Direct Growth","ticker":"INF277K01Z51","type":"mutual_fund","sector":"IT"},
    {"name":"Motilal Oswal Nasdaq 100 FOF - Direct Growth","ticker":"INF247L01AP2","type":"mutual_fund","sector":"International"},
    {"name":"DSP Midcap Fund - Direct Growth","ticker":"INF740K01PR5","type":"mutual_fund","sector":"Mid Cap"},
    {"name":"Bandhan ELSS Tax Saver Fund - Direct Growth","ticker":"","type":"mutual_fund","sector":"ELSS"},
    {"name":"Canara Robeco Bluechip Equity Fund - Direct Growth","ticker":"","type":"mutual_fund","sector":"Large Cap"},
    # ETFs
    {"name":"Nippon India ETF Nifty 50 BeES","ticker":"NIFTYBEES","type":"etf","sector":"Index"},
    {"name":"ICICI Prudential Nifty 50 ETF","ticker":"ICICINIFTY","type":"etf","sector":"Index"},
    {"name":"SBI ETF Nifty 50","ticker":"SETFNIFTY","type":"etf","sector":"Index"},
    {"name":"HDFC Nifty 50 ETF","ticker":"HDFCNIFTY","type":"etf","sector":"Index"},
    {"name":"Nippon India ETF Gold BeES","ticker":"GOLDBEES","type":"etf","sector":"Gold"},
    {"name":"ICICI Prudential Gold ETF","ticker":"","type":"etf","sector":"Gold"},
    {"name":"Nippon India ETF Bank BeES","ticker":"BANKBEES","type":"etf","sector":"Banking"},
    {"name":"Motilal Oswal Nasdaq 100 ETF","ticker":"MONAUTO","type":"etf","sector":"International"},
    {"name":"Nippon India ETF Liquid BeES","ticker":"LIQUIDBEES","type":"etf","sector":"Debt"},
    # Gold/SGB
    {"name":"Sovereign Gold Bond 2024-25 Series I","ticker":"SGBMAR26","type":"gold","sector":"Gold"},
    {"name":"Sovereign Gold Bond 2024-25 Series II","ticker":"SGBJUN26","type":"gold","sector":"Gold"},
    {"name":"Sovereign Gold Bond 2023-24 Series I","ticker":"SGBSEP25","type":"gold","sector":"Gold"},
    {"name":"Sovereign Gold Bond 2025-26","ticker":"SGB2526","type":"gold","sector":"Gold"},
    # Bonds/FD
    {"name":"RBI Floating Rate Savings Bond","ticker":"","type":"bond","sector":"Debt"},
    {"name":"SBI FD 1 Year","ticker":"","type":"fd","sector":"Debt"},
    {"name":"HDFC Bank FD 1 Year","ticker":"","type":"fd","sector":"Debt"},
    {"name":"Post Office Monthly Income Scheme","ticker":"","type":"other","sector":"Debt"},
    {"name":"National Savings Certificate","ticker":"","type":"other","sector":"Debt"},
    {"name":"Public Provident Fund (PPF)","ticker":"","type":"other","sector":"Debt"},
]
