// Nivesh Learn — course catalog + demo portfolio fields.
// Content: the Nivesh Learn curriculum (8 courses / 68 lessons). Data-driven:
// to add a course, append one object to COURSES. `core` holds trusted inline
// <b>/<i> markup rendered via dangerouslySetInnerHTML; `hook` uses {placeholder}
// tokens filled from DEMO (sample data until wired to the portfolio engine).

export interface LearnQuiz { q: string; opts: string[]; a: number; exp: string; }
export interface LearnLesson { _c?: number; id: string; t: string; min: number; core: string; hook: string; q: LearnQuiz; }
export interface LearnModule { title: string; lessons: LearnLesson[]; }
export interface LearnCourse { n: number; title: string; level: string; min: number; prereq: string; promise: string; modules: LearnModule[]; }

export const DEMO: Record<string, string> = {
  idle_cash:"1,80,000", sb_rate:"3.5", inflation:"6", annual_erosion:"4,500",
  sip_total:"25,000", age:"29", proj_60:"8.4 Cr", delay_cost:"22 L",
  monthly_spend:"65,000", ef_target:"3,90,000", ef_current:"1,20,000",
  equity_pct:"62", drawdown_est:"2,80,000",
  alloc_breakdown:"58% equity · 22% debt · 8% gold · 12% cash", goal_name:"Retirement",
  goal_years:"22", suggested_split:"75/25",
  fd_rate:"7", tax_slab:"30", post_tax:"4.9",
  fund_count:"9", amc_count:"5", stock_count:"240",
  low_nav_fund:"UTI Nifty 50 Index", high_nav_fund:"ICICI Bluechip",
  category_breakdown:"4 large-cap · 2 flexi · 1 mid · 1 small · 1 liquid", concentration_note:"That is a lot of large-cap overlap.",
  sample_fund:"Parag Parikh Flexi Cap",
  avg_ter:"0.9", portfolio_value:"18,40,000", annual_fee:"16,560",
  regular_count:"3", commission_cost:"12,800",
  load_amount:"2,10,000", load_date:"12 Sep 2026", load_cost:"2,100",
  sip_dates:"5th & 10th", stepup_gain:"46 L",
  kyc_status:"Validated", nominee_status:"Missing on 2 folios",
  overlap_pct:"58", debt_pct:"26", gold_pct:"8", target_split:"70/25/5",
  goal_list:"Retirement, Child education, Emergency fund", unbucketed_amount:"₹3,20,000",
  core_pct:"55", satellite_list:"1 mid-cap · 1 US index",
  redundant_pairs:"2", core_fund:"UTI Nifty 50 Index", ter:"0.20", te:"0.08", alpha:"1.2",
  debt_list:"Liquid Fund · Short Duration Fund", credit_flag:"All AAA — clean",
  india_pct:"92", intl_pct:"4",
  stock_pick:"HDFC Bank", rev_cagr:"14", margin:"22", cfo_ratio:"0.86",
  roce:"18", de:"0.4", pe:"19", sector_pe:"24", median_pe:"22", valuation_tag:"roughly fair",
  moat_stocks:"HDFC Bank, Asian Paints", no_moat_stocks:"a metals holding",
  flag_summary:"No major flags; one holding has rising receivables",
  top_position_pct:"14",
  top_stock:"Reliance", top_stock_pct:"11", top_sector:"Financials", sector_pct:"34",
  worst_pair:"Bluechip × Top 100", worst_overlap:"71",
  est_drawdown:"46", stated_tolerance:"30",
  t0_amount:"1,20,000", t3_amount:"6,40,000", locked_amount:"2,00,000", lock_details:"ELSS until Mar 2027",
  xirr:"12.4", bench:"13.1", xirr_inception:"12.9", best_holding:"Flexi Cap", worst_holding:"a thematic fund",
  sharpe_table:"0.9 · 0.7 · 1.1", low_sharpe_fund:"Small Cap Fund",
  fund_x:"Mid Cap Fund", beta:"1.3", alpha_verdict:"mostly beta, not skill",
  corr_summary:"two large-caps at +0.94; gold at −0.10", redundant_pair:"Bluechip × Top 100", corr_value:"0.94",
  factor_tilts:"small-cap + growth",
  stress_value:"9,80,000", ef_months:"6",
  pause_month:"Mar 2020", dip_pct:"34", pause_cost:"1,40,000",
  review_date:"15 Apr 2027",
  current_split:"72/28", drift_direction:"meaningfully",
  breach_date:"2 Feb 2026", annual_date:"1 Apr 2026",
  underweight_asset:"debt", months_to_balance:"7",
  ltcg_used:"40,000", ltcg_room:"85,000",
  smallcap_pct:"28", smallcap_target:"15",
  stcg_unrealized:"60,000", ltcg_unrealized:"2,40,000", tax_if_sold:"26,375",
  pre2023_amt:"1,10,000", post2023_amt:"90,000", slab:"30",
  harvest_room:"1,25,000", eligible_ltcg:"1,60,000",
  loss_cf:"45,000", loss_year:"FY 2023-24", unrealized_loss:"30,000", gains:"80,000",
  recent_units_pct:"35", stcg_portion:"21,000",
  better_regime:"new", regime_delta:"18,000", elss_verdict:"weakens the case for",
  rta_sources:"CAMS + KFintech", mismatch_count:"2",
  no_nominee_count:"2", cas_date:"30 Jun 2026"
};

export const COURSES: LearnCourse[] = [
{ n:1, title:`Basics of Investing`, level:`Beginner`, min:35, prereq:`none`,
  promise:`Know why money sitting still loses value, what the main options in India actually are, and how to start without gambling.`,
  modules:[
    { title:`Module 1 — Why invest at all`, lessons:[
      { id:`1.1`, t:`Inflation: the silent fee`, min:4,
        core:`Prices in India have historically risen <b>~5–6% a year</b>. Money in a savings account earning 3% is <b>losing</b> ~2–3% of purchasing power annually — a fee nobody shows you on a statement. ₹1 lakh kept in cash for 20 years buys roughly what ₹35–40k buys today. Investing isn't about getting rich; the first job is simply to not get quietly poorer.`,
        hook:`You hold ₹{idle_cash} in savings earning ~{sb_rate}%. At {inflation}% inflation, that's losing about ₹{annual_erosion} of buying power a year.`,
        q:{ q:`Your savings account pays 3.5% and inflation is 6%. What is your real return?`, opts:[`−2.5%`,`+3.5%`,`+9.5%`,`0% — they cancel out`], a:0, exp:`Real return = nominal minus inflation: 3.5% − 6% = −2.5%. Your money grows on paper but buys less each year.` } },
      { id:`1.2`, t:`Compounding, shown honestly`, min:5,
        core:`Compounding means returns earning returns. The honest part: it's boring for the first decade and explosive afterwards. ₹10,000/month at 12% is ~₹23L after 10 years — but ~₹98L after 20 and ~₹3.5Cr after 30. The lesson isn't "invest and get rich fast"; it's <b>the person who starts at 25 beats the person who starts at 35</b> even if the late starter invests twice as much.`,
        hook:`Your SIPs total ₹{sip_total}/month. Started at your age ({age}), at 12% that's ₹{proj_60} by 60. Delaying one year costs roughly ₹{delay_cost}.`,
        q:{ q:`Anu invests ₹5k/month from age 25 to 35 then stops. Raj invests ₹5k/month from 35 to 60. At 12%, who has more at 60?`, opts:[`Anu — her earlier money compounds longer`,`Raj — he invested for far more years`,`They end up about equal`,`Impossible to say without the fund name`], a:0, exp:`Anu's money gets an extra decade to compound. Time in the market beats amount invested — starting early is the biggest lever.` } },
      { id:`1.3`, t:`Emergency fund before anything`, min:4,
        core:`Before any market investment: <b>6 months of expenses</b> somewhere safe and instantly reachable (savings + liquid fund split works well). Without it, the first job loss or medical bill forces you to sell investments at whatever the price is that day — usually the worst day. An emergency fund isn't an investment; it's what lets your investments stay invested.`,
        hook:`Your monthly spend looks like ₹{monthly_spend}. A full emergency fund for you is ₹{ef_target}; you currently have ₹{ef_current} in liquid form.`,
        q:{ q:`What is the main job of an emergency fund?`, opts:[`To keep you from selling investments at a bad time`,`To earn the highest possible return`,`To beat inflation over 20 years`,`To reduce your income tax`], a:0, exp:`Its job is availability, not returns — it lets your real investments stay invested through a shock instead of being sold at the worst moment.` } },
      { id:`1.4`, t:`Risk and return are the same dial`, min:4,
        core:`There is no high-return, no-risk product; anyone offering one is either hiding the risk or lying. FD → low risk, ~6–7%. Debt funds → slightly more of both. Equity → high long-run returns (~11–13% historically) with gut-wrenching interim drops (−30 to −50% in bad years). For a long-term investor "risk" mostly means <b>volatility you must sit through</b>, not permanent loss — but only if you're diversified and don't sell in a panic.`,
        hook:`Your portfolio is {equity_pct}% equity. In a 2020-style crash it would have temporarily dropped about ₹{drawdown_est}. Could you watch that without selling?`,
        q:{ q:`A scheme promises 24% "guaranteed" returns. What do you know for sure?`, opts:[`Something is being hidden — high return without risk doesn't exist`,`It's a great deal you should act on fast`,`It's normal for equity mutual funds`,`The return is low for the risk`], a:0, exp:`Guaranteed high returns are a contradiction. The risk is hidden or it's a scam — walk away.` } }
    ]},
    { title:`Module 2 — The menu of options`, lessons:[
      { id:`2.1`, t:`The Indian investor's menu`, min:5,
        core:`The main aisles: <b>FDs/RDs</b> (safe, taxed at slab, barely beats inflation), <b>PPF/EPF</b> (safe, tax-friendly, locked in), <b>debt funds</b> (bond baskets), <b>equity funds</b> (stock baskets, the workhorse for long-term goals), <b>direct stocks</b> (highest control, highest skill), <b>gold</b> (inflation hedge, no cash flow), <b>real estate</b> (lumpy, illiquid). Most people need only three aisles: emergency cash, debt for near goals, equity for far goals.`,
        hook:`Your money today: {alloc_breakdown}. Notice what's missing for your {goal_name} goal.`,
        q:{ q:`Which is generally the best vehicle for a goal 15 years away?`, opts:[`Equity mutual funds`,`A 5-year fixed deposit`,`A liquid fund`,`Gold only`], a:0, exp:`Over 15 years equity's volatility smooths out and its higher long-run return compounds. Long horizons are where equity shines.` } },
      { id:`2.2`, t:`Goals decide products, not tips`, min:4,
        core:`The order of decisions: <b>goal → time horizon → asset class → product</b>. A goal under 3 years away has no business being in equity, however good the "tip." A goal 15 years away has no business sitting in an FD. When someone recommends a product before asking your horizon, they're selling, not advising.`,
        hook:`You marked '{goal_name}' as {goal_years} years away. That horizon points to roughly {suggested_split} equity/debt.`,
        q:{ q:`You need ₹4L for a wedding in 18 months. Where does it go?`, opts:[`Debt / FD-type instruments`,`A small-cap equity fund`,`Direct stocks`,`A thematic "AI" fund`], a:0, exp:`18 months is too short to ride out an equity drop. Short horizon means capital safety over return.` } },
      { id:`2.3`, t:`Real returns and taxes: the two leaks`, min:4,
        core:`What matters is <b>post-tax, post-inflation</b> return. An FD at 7% for someone in the 30% slab is ~4.9% post-tax — barely inflation. Equity funds' long-term gains are taxed at 12.5% above ₹1.25L a year, one of the gentler taxes in the system. Learning to think in real, post-tax terms is the single biggest upgrade to financial decisions.`,
        hook:`Your FDs earn {fd_rate}%. In your {tax_slab}% slab, that's {post_tax}% post-tax — against {inflation}% inflation.`,
        q:{ q:`7% FD, 30% slab, 6% inflation → real post-tax return?`, opts:[`≈ −1.1%`,`+7%`,`+4.9%`,`+1%`], a:0, exp:`7% × (1 − 0.30) = 4.9% post-tax; minus 6% inflation ≈ −1.1%. The FD quietly loses real value.` } },
      { id:`2.4`, t:`Scams and red flags`, min:5,
        core:`The costume changes, the script doesn't: guaranteed high returns, urgency ("closing this week"), unregistered advisors, returns paid from new deposits, WhatsApp/Telegram "pump" groups. Two-minute checks: is the entity <b>SEBI-registered</b> (verifiable on sebi.gov.in)? Is the return claim above ~12–14% <i>and</i> "assured"? Are you being rushed? Any yes → walk away.`,
        hook:`Tip: forward any 'investment opportunity' message to the copilot — it will run the red-flag checklist for you.`,
        q:{ q:`Which single word in a pitch is the strongest red flag?`, opts:[`"Guaranteed" (with high returns)`,`"Diversified"`,`"Long-term"`,`"Index"`], a:0, exp:`Legitimate market products can't promise returns. "Guaranteed" plus high returns is the loudest warning sign.` } }
    ]}
  ] },
{ n:2, title:`Starter Kit for Mutual Fund Investing`, level:`Beginner`, min:45, prereq:`Basics of Investing`,
  promise:`Understand exactly what a mutual fund is, what it costs, how to pick your first fund without a tip, and how to start a SIP end-to-end.`,
  modules:[
    { title:`Module 1 — What you actually own`, lessons:[
      { id:`1.1`, t:`A mutual fund is a basket with a manager`, min:4,
        core:`You pool money with thousands of others; a fund house (AMC) buys a basket of stocks/bonds; you own <b>units</b> of the basket. Regulated by SEBI, assets held by a separate custodian — the AMC going bust doesn't take your money with it. The value of one unit is the NAV.`,
        hook:`You own units across {fund_count} funds from {amc_count} fund houses — effectively small slices of {stock_count}+ companies.`,
        q:{ q:`If your AMC shuts down, your money is…`, opts:[`still yours — assets sit with a custodian, overseen by SEBI`,`lost with the company`,`converted to the AMC's shares`,`frozen permanently`], a:0, exp:`Assets are held by a separate custodian/trustee and SEBI oversees any transfer or wind-down at NAV. The AMC is just the manager.` } },
      { id:`1.2`, t:`NAV isn't a price tag`, min:3,
        core:`A fund at NAV ₹15 is <b>not</b> "cheaper" than one at ₹500. NAV is just (assets ÷ units). What matters is the <b>percentage</b> growth of the basket. A ₹10-NAV fund and a ₹500-NAV fund holding identical stocks give identical returns. "New fund at ₹10, buy low!" is a sales trick, not math.`,
        hook:`Your lowest-NAV fund ({low_nav_fund}) and highest ({high_nav_fund}) — compare their 3-year returns in the app and see which actually grew more.`,
        q:{ q:`Fund A NAV ₹12, Fund B NAV ₹480, same portfolio. After a 10% market rise, which gained more?`, opts:[`Neither — both rose 10%`,`Fund A, it's cheaper`,`Fund B, it's more valuable`,`Depends on the AMC`], a:0, exp:`NAV is assets ÷ units. Identical holdings rise by the same percentage regardless of the NAV number.` } },
      { id:`1.3`, t:`The map of fund types`, min:5,
        core:`<b>Equity</b> (large/mid/small-cap, flexi-cap, sectoral), <b>debt</b> (liquid, short-duration, gilt, corporate bond), <b>hybrid</b> (mixes), <b>index funds</b> (copy an index like Nifty 50 at very low cost), <b>ELSS</b> (equity with an 80C tax break, 3-year lock-in). Rule of thumb for a first-timer: a broad index fund or flexi-cap covers 90% of the need; sectoral/thematic funds are seasoning, not the meal.`,
        hook:`Your mix today: {category_breakdown}. {concentration_note}`,
        q:{ q:`Which fund type simply copies an index at minimal cost?`, opts:[`Index fund`,`Sectoral fund`,`ELSS`,`Liquid fund`], a:0, exp:`An index fund mirrors a benchmark like the Nifty 50 at very low expense — its whole job is to track cheaply.` } },
      { id:`1.4`, t:`Reading a fund page without fear`, min:5,
        core:`The five things worth reading: <b>category and benchmark; expense ratio; 5-year returns vs the benchmark</b> (not vs a savings account); <b>top-10 holdings</b> and their weight; <b>fund-manager tenure</b>. Ignore: star ratings alone, 1-month returns, ads. A fund beating its benchmark over 5+ years with reasonable costs is doing its one job.`,
        hook:`Open {sample_fund} in the app — the copilot has annotated its page with these five fields highlighted.`,
        q:{ q:`A fund returned 14% last year. Good or bad?`, opts:[`Can't say — you must compare it to its benchmark`,`Good, 14% is high`,`Bad, equity should do more`,`Good, it beat inflation`], a:0, exp:`If the benchmark did 18%, that 14% is underperformance. Returns only mean something measured against the benchmark.` } }
    ]},
    { title:`Module 2 — What it costs you`, lessons:[
      { id:`2.1`, t:`Expense ratios, decoded`, min:4,
        core:`The expense ratio is deducted <b>daily</b> from the fund's assets before you see NAV — invisible but real. 1% sounds small; over 20 years it can eat 15–20% of your final corpus. Index funds run at 0.1–0.3%; active equity funds 0.5–1.5% (direct plans). An active fund must beat its index by <i>more than</i> its extra fee to be worth it.`,
        hook:`Your weighted average expense ratio is {avg_ter}%. On your ₹{portfolio_value} portfolio, that's ₹{annual_fee}/year in fees.`,
        q:{ q:`Fund X (index, 0.2%) and Fund Y (active, 1.2%) both match the market before fees. After 20 years, Y's investor has…`, opts:[`noticeably less — the 1% gap compounds against them`,`the same amount`,`more, active is better`,`slightly more after tax`], a:0, exp:`A 1% annual fee gap compounds every year, quietly costing a meaningful slice of the final corpus.` } },
      { id:`2.2`, t:`Direct vs regular plans`, min:4,
        core:`Every fund has two doors: <b>regular</b> (via a distributor paid ~0.5–1%/year out of <i>your</i> returns, forever) and <b>direct</b> (bought yourself, no commission). Same fund, same manager, same stocks — the direct plan simply compounds faster. Over 15 years the gap is often 10–15% of the final corpus. Distributors can be worth it if they give real advice; know what you're paying.`,
        hook:`{regular_count} of your funds are regular plans, costing you roughly ₹{commission_cost}/year in embedded commission.`,
        q:{ q:`Same fund, direct vs regular, 15 years — who ends with more?`, opts:[`Direct — the lower expense ratio compounds`,`Regular — the distributor adds value`,`They're identical`,`Whichever has the higher NAV`], a:0, exp:`Direct plans carry no distributor commission, so the lower cost compounds year after year into a larger corpus.` } },
      { id:`2.3`, t:`Exit loads and lock-ins`, min:3,
        core:`An <b>exit load</b> is a small penalty (typically 1%) for redeeming within a set window (often 1 year) — designed to discourage churn. <b>ELSS</b> funds lock money for 3 years, period. Check both <i>before</i> investing, and check the load clock before redeeming; waiting a few weeks is sometimes free money.`,
        hook:`₹{load_amount} of your holdings still carries an exit load until {load_date}. Redeeming today would cost ₹{load_cost}.`,
        q:{ q:`You invested ₹1L eleven months ago; the fund has a 1% load for redemptions under 12 months. Redeeming now costs…`, opts:[`~₹1,000+ — waiting a month makes it zero`,`nothing, loads don't apply to profits`,`3 years of lock-in`,`your entire gain`], a:0, exp:`You're inside the 12-month window, so a ~1% exit load applies. Waiting past the window makes it free.` } }
    ]},
    { title:`Module 3 — Doing it`, lessons:[
      { id:`3.1`, t:`SIP: automation beats willpower`, min:4,
        core:`A SIP invests a fixed amount monthly, automatically. Two quiet superpowers: it removes the "is now a good time?" question (you buy every month, cheap months included — <b>rupee-cost averaging</b>), and it removes willpower from the loop. The best SIP amount is the one you never have to pause. Step it up 10% with every salary hike.`,
        hook:`Your SIPs run on the {sip_dates} of each month, totaling ₹{sip_total}. A 10% step-up adds ₹{stepup_gain} to your 20-year corpus.`,
        q:{ q:`The market falls 15% mid-month. Your SIP should…`, opts:[`run as usual — falling months buy more units cheaply`,`be paused until it recovers`,`be doubled immediately`,`be switched to an FD`], a:0, exp:`Falling months are exactly where a SIP buys more units for the same rupees. Pausing forfeits that advantage.` } },
      { id:`3.2`, t:`KYC to first SIP, end-to-end`, min:5,
        core:`The mechanics: one-time <b>KYC</b> (PAN + Aadhaar, fully online); choose a platform (prefer ones offering <i>direct</i> plans); pick the fund; set SIP amount and date; set up the bank <b>mandate</b> (e-NACH); register a <b>nominee</b> (mandatory, 2 minutes, saves your family months). Done — first debit next cycle.`,
        hook:`Your KYC status: {kyc_status}. Nominee on record: {nominee_status}.`,
        q:{ q:`Which step protects your family if something happens to you?`, opts:[`Nomination`,`Choosing a direct plan`,`Setting the SIP date`,`Picking a low-NAV fund`], a:0, exp:`Without a registered nominee, claiming units requires a painful legal process. Nomination takes two minutes and prevents that.` } },
      { id:`3.3`, t:`Your first portfolio: boring on purpose`, min:4,
        core:`A perfectly good starter portfolio is <b>1–3 funds</b>: a Nifty 50 or broad index fund as the core, optionally a flexi-cap, plus a liquid fund for the emergency buffer. Not ten funds. More funds ≠ more diversification — often it's the same 50 stocks bought five times (overlap). Start boring; add complexity only when you can explain why.`,
        hook:`Your current fund count: {fund_count}. The copilot estimates {overlap_pct}% overlap among your equity funds.`,
        q:{ q:`The main problem with owning 8 large-cap funds is…`, opts:[`overlap — the same stocks repeatedly, paying 8 expense ratios`,`too little risk`,`they can't be held in one folio`,`they aren't SEBI-regulated`], a:0, exp:`Large-cap funds share the same top stocks, so you own the same names five times over while paying eight fees. That's cost, not diversification.` } }
    ]}
  ] },
{ n:3, title:`How to Build Your Portfolio`, level:`Beginner–Intermediate`, min:40, prereq:`MF Starter Kit`,
  promise:`A repeatable method: core-satellite structure, the right fund count, and a one-page Investment Policy Statement you can defend.`,
  modules:[
    { title:`Module 1 — The blueprint`, lessons:[
      { id:`1.1`, t:`Asset allocation is 90% of the game`, min:5,
        core:`Research consistently shows the <b>equity/debt/gold split</b> explains most of a portfolio's long-run behaviour — far more than which specific funds you pick. Decide the split first, from horizon and stomach: a common frame is equity % ≈ money you won't touch for 7+ years, with "100 minus age" as a rough sanity check, then adjust for your actual reaction to losses.`,
        hook:`Your current split: {equity_pct}/{debt_pct}/{gold_pct}. Your goals and horizon suggest roughly {target_split}.`,
        q:{ q:`Two investors hold identical funds, but one is 80/20 equity/debt and the other 20/80. Their outcomes differ mainly because of…`, opts:[`allocation, not fund selection`,`the fund manager`,`luck`,`expense ratios`], a:0, exp:`The equity/debt split drives most of the difference in return and risk — allocation dominates fund choice.` } },
      { id:`1.2`, t:`Goal buckets: one portfolio per job`, min:5,
        core:`Don't build one blob of money; build <b>buckets</b>. Each goal gets a horizon, a target amount, and its own allocation: <3 years → debt/FD; 3–7 years → hybrid/balanced; 7+ years → equity-heavy. This turns "should I invest in equity?" into "which bucket is this money for?" — a question with an actual answer.`,
        hook:`Your goals on file: {goal_list}. {unbucketed_amount} of your money isn't assigned to any goal yet.`,
        q:{ q:`House down payment in 2 years — which bucket?`, opts:[`Debt / FD bucket`,`Small-cap equity`,`Gold`,`Flexi-cap equity`], a:0, exp:`Two years is too short for equity risk. Near-term goals belong in capital-stable debt/FD instruments.` } },
      { id:`1.3`, t:`Core and satellite`, min:4,
        core:`Structure the equity bucket as <b>core</b> (60–80%: broad index/flexi-cap — cheap, diversified, boring) plus <b>satellite</b> (20–40%: mid/small-cap, international, or a theme you genuinely understand). The core guarantees you capture the market; satellites are where you take deliberate, sized bets. If a satellite fails it stings; it can't sink you.`,
        hook:`Your core today is {core_pct}% of equity; satellites are {satellite_list}.`,
        q:{ q:`Your friend's "AI theme fund" tip belongs in…`, opts:[`the satellite sleeve, sized small`,`the core, it's the future`,`your emergency fund`,`your debt bucket`], a:0, exp:`Themes are satellites — deliberate, small, sized bets. They never belong in the core that must reliably capture the market.` } },
      { id:`1.4`, t:`How many funds is enough`, min:4,
        core:`For most investors: <b>3–6 funds total</b>. One broad equity core, maybe one mid/small-cap, one international (optional), one or two debt funds, done. Beyond that, each new fund adds overlap and tracking work, not diversification. The test before adding any fund: "what does this hold that I don't already own?"`,
        hook:`You hold {fund_count} funds. The copilot found {redundant_pairs} pairs with >50% overlap — candidates to consolidate.`,
        q:{ q:`Adding a 4th large-cap fund to three you own mostly adds…`, opts:[`overlap and fees, not diversification`,`real diversification`,`lower risk`,`a tax benefit`], a:0, exp:`A fourth large-cap holds the same top stocks as the other three. You add fees and tracking work, not diversification.` } }
    ]},
    { title:`Module 2 — Assembling it`, lessons:[
      { id:`2.1`, t:`Choosing the core`, min:5,
        core:`For the core, <b>cost and consistency beat brilliance</b>: broad index funds (Nifty 50 / Nifty 500) with low tracking error and expense <0.3%, or a flexi-cap with 5+ years of beating its benchmark under the same manager. You're hiring the core to be reliable, not exciting.`,
        hook:`Candidate check: {core_fund} — expense {ter}%, tracking error {te}%, benchmark gap over 5y: {alpha}%.`,
        q:{ q:`The most important number for an index fund is…`, opts:[`cost + tracking error`,`last month's return`,`its star rating`,`its NAV`], a:0, exp:`An index fund's whole job is copying the index cheaply and accurately — so low cost and low tracking error are what matter.` } },
      { id:`2.2`, t:`Debt for stability, not excitement`, min:4,
        core:`The debt bucket's job is to <b>be there when equity isn't</b>. Prefer liquid/short-duration funds with high-credit-quality portfolios; skip "high yield" debt funds chasing an extra 1% by lending to shaky borrowers — that's equity-like risk with FD-like returns. Remember: debt fund gains (units bought after 1 Apr 2023) are taxed at your slab.`,
        hook:`Your debt holdings: {debt_list}. Credit quality flag: {credit_flag}.`,
        q:{ q:`A debt fund yielding 3% above peers most likely…`, opts:[`is taking credit risk — lending to lower-rated borrowers`,`has a better manager`,`is a safer choice`,`is an index fund`], a:0, exp:`Extra yield in debt almost always means extra credit risk. That's equity-like risk sitting in the sleeve meant to be your safety.` } },
      { id:`2.3`, t:`Gold and international: the seasoning`, min:4,
        core:`5–10% <b>gold</b> (SGBs where available, or gold funds/ETFs) hedges inflation and rupee shocks; 5–15% <b>international equity</b> (mostly US) hedges the single-country risk of everything else you own being Indian — your job, house, and portfolio all bet on one economy. Both are diversifiers, not return engines; note most international funds are currently taxed like debt.`,
        hook:`Your India concentration: {india_pct}% of investable assets, plus your salary. International allocation today: {intl_pct}%.`,
        q:{ q:`The strongest argument for a salaried Indian to hold international equity is…`, opts:[`everything else they have already depends on India`,`the US always beats India`,`it's tax-free`,`it has no volatility`], a:0, exp:`Your salary, home, and portfolio are usually all Indian bets. International equity diversifies that single-country concentration.` } },
      { id:`2.4`, t:`Write it down: your one-page IPS`, min:5,
        core:`An <b>Investment Policy Statement</b> is one page: target allocation, fund list with each fund's role, SIP amounts, rebalancing rule, and — most important — <b>what you will do in a crash</b> (usually: nothing, or buy). Written when calm, read when panicking. Portfolios fail in moments of emotion; the IPS is the note from your smarter self.`,
        hook:`The copilot has drafted your IPS from this course's answers — review and sign it in the app.`,
        q:{ q:`The IPS's most valuable line is the one describing…`, opts:[`what you'll do in a crash — decided in advance`,`last year's returns`,`your favourite fund`,`the AMC's phone number`], a:0, exp:`The crash-plan line, written while calm, is what stops emotional selling later. That's the IPS's whole point.` } }
    ]}
  ] },
{ n:4, title:`Stocks: Fundamental & Technical Analysis`, level:`Intermediate`, min:70, prereq:`How to Build Your Portfolio`,
  promise:`Read an annual report and a price chart without flinching. Value a business three rough ways, spot accounting red flags, and know what technicals can and cannot do.`,
  modules:[
    { title:`Module 1 — Fundamental analysis: the business`, lessons:[
      { id:`1.1`, t:`A stock is a business, not a ticker`, min:4,
        core:`Buying a share = buying a slice of future profits. Everything in fundamental analysis flows from one question: <b>"how much cash will this business hand its owners over time, and what am I paying for that?"</b> Price is what you pay; value is what you get; the gap between them is the entire game.`,
        hook:`You own {stock_count} stocks. Pick one — the copilot will walk this course's checklist on it with you.`,
        q:{ q:`A stock falling 20% on no business news means the business is…`, opts:[`worth roughly the same — only the price changed`,`definitely in trouble`,`always a buy`,`worth 20% less`], a:0, exp:`Price moved, value didn't. Whether the drop is an opportunity depends entirely on value vs price — not the drop itself.` } },
      { id:`1.2`, t:`The three financial statements, minimum viable`, min:6,
        core:`<b>P&L</b>: did it earn? (revenue → operating profit → net profit; watch margins over 5 years). <b>Balance sheet</b>: what it owns vs owes (debt-to-equity, and whether "assets" are real). <b>Cash flow</b>: did profit turn into cash? The classic trap: profits growing while operating cash flow shrinks — often aggressive accounting. If you read only one statement, read cash flow.`,
        hook:`For {stock_pick}: 5-year revenue CAGR {rev_cagr}%, net margin {margin}%, CFO/net profit ratio {cfo_ratio}.`,
        q:{ q:`Profits up 3 straight years, operating cash flow down 3 straight years. Reaction?`, opts:[`Suspicion — profit that never becomes cash may be accounting`,`Celebrate the growth`,`Buy more`,`Ignore it, cash flow is noise`], a:0, exp:`Real profit eventually shows up as cash. A persistent gap between the two is a classic warning of aggressive accounting.` } },
      { id:`1.3`, t:`Ratios that matter (and the ones that lie alone)`, min:6,
        core:`A working kit: <b>ROE/ROCE</b> (does the business earn well on its capital? 15%+ sustained is good), <b>debt-to-equity</b> (<1 for most sectors), <b>operating margin trend</b>, <b>P/E and P/B</b> (price tags — only meaningful vs the company's own history and its sector). No ratio works alone: a low P/E can mean "cheap" or "dying"; high ROE with high debt is borrowed brilliance.`,
        hook:`{stock_pick}: ROCE {roce}%, D/E {de}, P/E {pe} vs sector median {sector_pe}.`,
        q:{ q:`A stock at P/E 6 while its sector trades at 22 is…`, opts:[`either a bargain or a business in trouble`,`always a bargain`,`always a value trap`,`overpriced`], a:0, exp:`A low P/E raises the question — cheap or dying? — it doesn't answer it. You have to look at why it's cheap.` } },
      { id:`1.4`, t:`Moats: why profits persist`, min:5,
        core:`High returns attract competitors; only businesses with <b>moats</b> keep them: brands (pricing power), network effects, switching costs, cost advantages, regulatory licenses. The test: "if a rival with ₹10,000 Cr attacked this business, what would protect it?" No answer → today's fat margins are tomorrow's price war.`,
        hook:`Of your holdings, the copilot tags {moat_stocks} as having identifiable moats and {no_moat_stocks} as commodity businesses.`,
        q:{ q:`Which is the strongest moat: lowest price today, a beloved brand, or a hot product?`, opts:[`A beloved brand — pricing power endures`,`Lowest price today`,`A hot product`,`All are equal`], a:0, exp:`Low prices and hot products get copied. A trusted brand keeps pricing power and margins over time — a durable moat.` } },
      { id:`1.5`, t:`Valuation: three rough lenses`, min:6,
        core:`(1) <b>Historical multiple</b>: is today's P/E above/below the stock's own 10-year band? (2) <b>Peer multiple</b>: vs comparables, adjusted for growth and quality. (3) <b>Earnings yield vs bond yield</b>: E/P vs the 10-year G-Sec — a sanity check on whether equity risk is paid for. Precision is fake; direction is real. You're deciding "roughly cheap, fair, or expensive," not a target to two decimals.`,
        hook:`{stock_pick} trades at {pe} vs its 10-year median {median_pe} — the copilot's rough tag: {valuation_tag}.`,
        q:{ q:`The honest output of valuation work is…`, opts:[`a range and a direction ("roughly expensive")`,`a precise target price`,`a guaranteed return`,`the exact fair value`], a:0, exp:`Valuation gives you a direction and a range, not a decimal-precise target. Fake precision is a trap.` } },
      { id:`1.6`, t:`Red flags and forensic basics`, min:5,
        core:`Walk-away signals: promoter pledging rising, auditor resignations, receivables growing much faster than sales, frequent "one-time" exceptional items, related-party transactions, CFO exits, debt refinanced endlessly. Any two together → skip; there are 5,000 other listed companies.`,
        hook:`Red-flag scan of your holdings: {flag_summary}.`,
        q:{ q:`Sales up 15%, receivables up 60%. Possible reading?`, opts:[`The company may be booking sales it hasn't collected`,`Business is simply booming`,`It's paying down debt`,`Nothing unusual`], a:0, exp:`Receivables far outrunning sales is a classic aggressive-revenue flag — sales booked but not yet collected.` } }
    ]},
    { title:`Module 2 — Technical analysis: the crowd`, lessons:[
      { id:`2.1`, t:`What technicals actually are`, min:4,
        core:`Technical analysis studies <b>price and volume</b> — the footprints of crowd behaviour — to assess probabilities of short-term moves. It says nothing about business value. Honest framing: fundamentals tell you <i>what</i> to buy, technicals can help with <i>when</i> (entries/exits) and with risk placement. Anyone claiming charts predict the future is selling a course.`,
        hook:``,
        q:{ q:`Technicals are most defensibly used for…`, opts:[`timing entries/exits and placing stop-losses`,`deciding if a business is good`,`predicting next year's price`,`valuing a company`], a:0, exp:`Charts describe crowd behaviour and help with timing and risk placement — not with whether the underlying business is worth owning.` } },
      { id:`2.2`, t:`Trend, support, resistance`, min:5,
        core:`Trend = the market's prevailing direction (higher highs/lows = uptrend). Support/resistance = price <b>zones</b> where buying/selling repeatedly appeared — zones, not lines. The most useful single habit: <b>don't fight the trend</b>; the most common beginner loss is buying falling knives because they "look cheap on the chart."`,
        hook:``,
        q:{ q:`A stock breaks below a support zone it held four times. Conventional reading?`, opts:[`The zone often flips to resistance; downside risk rose`,`It must bounce back immediately`,`Support always holds the fifth time`,`Volume no longer matters`], a:0, exp:`Broken support commonly becomes resistance, and the failure of a repeatedly-held level signals increased downside risk.` } },
      { id:`2.3`, t:`Moving averages and momentum`, min:5,
        core:`Moving averages (50/200-day) smooth noise into trend; price above a rising 200-DMA is the simplest "healthy trend" filter. Momentum oscillators (RSI) flag stretched moves — RSI >70/<30 as overbought/oversold <i>within context</i>. These are weather instruments, not oracles: they describe conditions, they don't guarantee outcomes.`,
        hook:``,
        q:{ q:`RSI at 78 in a strong uptrend means…`, opts:[`the move is stretched — a caution flag, not an automatic sell`,`sell immediately`,`the trend has ended`,`buy with leverage`], a:0, exp:`Strong trends can stay "overbought" for months. RSI 78 is a caution flag in context, not a mechanical sell signal.` } },
      { id:`2.4`, t:`Volume, patterns, and self-deception`, min:5,
        core:`Volume validates: breakouts on high volume mean crowd conviction; on thin volume, suspicion. Chart patterns (flags, head-and-shoulders) are pattern-recognition aids with modest hit rates — dangerous when treated as certainties. The real lesson: humans see patterns in randomness; every technical signal needs a <b>risk plan for being wrong</b>.`,
        hook:``,
        q:{ q:`A breakout on volume 30% below average deserves…`, opts:[`skepticism — without participation, breakouts often fail`,`full confidence`,`immediate leverage`,`no stop-loss`], a:0, exp:`Breakouts need participation. Thin volume means little conviction behind the move, and such breakouts frequently fail.` } },
      { id:`2.5`, t:`Position sizing and stop-losses`, min:5,
        core:`The skill that decides survival: <b>never risk more than 1–2% of capital on one idea</b>. Size = (capital × risk%) ÷ (entry − stop). A stop-loss is the price at which your thesis is wrong — decided <i>before</i> entry, honoured without negotiation. Traders die not from being wrong, but from being wrong big.`,
        hook:`Your largest single-stock position is {top_position_pct}% of your portfolio — the copilot can stress-test what a 40% drop there does.`,
        q:{ q:`₹5L capital, 1% risk rule, entry ₹200, stop ₹180. Max shares?`, opts:[`250 shares`,`2,500 shares`,`25 shares`,`500 shares`], a:0, exp:`Risk budget = ₹5,000 (1% of ₹5L). Risk per share = ₹20 (₹200 − ₹180). 5,000 ÷ 20 = 250 shares.` } },
      { id:`2.6`, t:`Investor vs trader: pick a lane per rupee`, min:4,
        core:`Both approaches can work; mixing them mid-position is how money dies — buying as a "trade," losing 20%, and rebranding it a "long-term investment" is the most expensive lie in markets. Decide the lane <i>before</i> buying, write it down, and remember the tax line: intraday profits are speculative business income; F&O is business income; delivery gains are capital gains.`,
        hook:``,
        q:{ q:`Your "2-week trade" is down 25%. The disciplined move is…`, opts:[`honour the stop and exit`,`call it a long-term investment now`,`double down to average`,`ignore it for 5 years`], a:0, exp:`Converting a failed trade into an "investment" abandons the plan that sized it. The pre-set stop decides — honour it and exit.` } }
    ]}
  ] },
{ n:5, title:`Risk Management & Portfolio Analysis — Basic`, level:`Intermediate`, min:35, prereq:`How to Build Your Portfolio`,
  promise:`See the risks already inside your portfolio — concentration, overlap, volatility, liquidity — and the simple numbers that measure them.`,
  modules:[
    { title:`Lessons`, lessons:[
      { id:`1`, t:`Risk is what's left after the plan`, min:4,
        core:`Risk isn't "the market falls" — that's certain, eventually. Risk is <b>permanent damage</b>: forced selling at lows, concentration blowing up, inflation quietly winning, or you abandoning the plan. Every tool in this course targets one of those four.`,
        hook:``,
        q:{ q:`For a 25-year-old with a 30-year horizon and an emergency fund, the biggest real risk is…`, opts:[`abandoning the plan (or under-investing)`,`a market crash next year`,`a single bad quarter`,`a small fee`], a:0, exp:`With a long horizon and a cushion, short-term volatility isn't the threat — quitting the plan or not investing enough is.` } },
      { id:`2`, t:`Concentration: the risk you chose without noticing`, min:5,
        core:`Check four axes: <b>single stock</b> (>10% of portfolio = flag), <b>single sector</b> (>25–30% = flag), <b>single AMC</b>, <b>single country</b>. Concentration includes your life: working in IT + holding IT funds + IT stock ESOPs = one bet worn three ways.`,
        hook:`Your top stock exposure across funds and direct holdings combined: {top_stock} at {top_stock_pct}%. Sector tilt: {top_sector} at {sector_pct}%.`,
        q:{ q:`You work at an IT firm, hold its ESOPs, and own a tech fund. A tech downturn hits your…`, opts:[`salary, ESOPs, and portfolio simultaneously`,`portfolio only`,`ESOPs only`,`none of them`], a:0, exp:`That's one bet worn three ways — a single sector event hits your income and both pools of savings at once.` } },
      { id:`3`, t:`Overlap: diversification that isn't`, min:5,
        core:`Two funds diversify only if they hold <b>different things</b>. Indian large-cap funds routinely share 50–70% of holdings — the top of the Nifty appears in all of them. Measuring: compare top-25 holdings pairwise; over ~50% common weight = redundant pair. Fix by consolidating into the better fund, not adding a third.`,
        hook:`Your equity funds overlap {overlap_pct}% on average; worst pair: {worst_pair} at {worst_overlap}%.`,
        q:{ q:`Three large-cap funds with 65% mutual overlap give you roughly the diversification of…`, opts:[`one fund — with three expense ratios`,`three funds`,`a whole index`,`a balanced portfolio`], a:0, exp:`High overlap means you effectively own one basket while paying three fees. That's cost, not diversification.` } },
      { id:`4`, t:`Volatility and drawdown, in plain sight`, min:5,
        core:`Two numbers describe the ride: <b>standard deviation</b> (how bumpy) and <b>maximum drawdown</b> (worst peak-to-trough fall — the number your stomach meets). Equity funds have historically drawn down 30–60% in crises and recovered; knowing <i>your</i> portfolio's likely drawdown before it happens is the difference between holding and panicking.`,
        hook:`Backtested on 2008/2020, your current mix would have drawn down about {est_drawdown}%. Your stated tolerance was {stated_tolerance}%.`,
        q:{ q:`Max drawdown measures…`, opts:[`the worst peak-to-trough fall`,`the average yearly return`,`the expense ratio`,`the dividend yield`], a:0, exp:`Maximum drawdown is the largest drop from a peak to a following trough — the loss you'd have seen buying at the top.` } },
      { id:`5`, t:`Liquidity: can you get out when you must?`, min:4,
        core:`Liquidity risk hides until needed: small-cap funds can gate redemptions in panics, real estate takes months, ELSS is locked 3 years, FDs charge penalties. Map every holding by "<b>days to cash without meaningful loss</b>," and keep the emergency layer truly liquid.`,
        hook:`Liquidity map: ₹{t0_amount} same-day, ₹{t3_amount} within 3 days, ₹{locked_amount} locked ({lock_details}).`,
        q:{ q:`Which is the most liquid: ELSS units, a liquid fund, or a small-cap fund in a crash?`, opts:[`The liquid fund`,`ELSS units`,`The small-cap fund`,`They're equally liquid`], a:0, exp:`ELSS is locked for 3 years and small-caps can be hard to exit in a panic. A liquid fund is designed to convert to cash quickly.` } },
      { id:`6`, t:`Benchmarks: is your portfolio actually working?`, min:4,
        core:`Every portfolio needs a <b>fair benchmark</b> — e.g., a blended index matching your allocation (70% Nifty 500 + 30% bond index for a 70/30 portfolio). Comparing to the Sensex alone, or to a friend's returns, is noise. Underperforming your blend for 3+ years is a signal; for 3 months it's weather.`,
        hook:`Your 3-year XIRR: {xirr}% vs your blended benchmark's {bench}%.`,
        q:{ q:`A 60/40 portfolio returning 11% while Nifty returned 15% has…`, opts:[`not necessarily underperformed — compare to a 60/40 blend`,`clearly failed`,`beaten the market`,`taken too much risk`], a:0, exp:`40% of it was never trying to match Nifty. Judge it against a blended 60/40 benchmark, not the equity index alone.` } },
      { id:`7`, t:`XIRR: the only return number that doesn't lie to you`, min:4,
        core:`With SIPs and irregular cash flows, simple "absolute return" misleads. <b>XIRR</b> accounts for <i>when</i> each rupee entered, giving your true annualized return — the number comparable to FD rates and fund returns. If you learn one formula from this course, it's this one (and your app computes it for you).`,
        hook:`Your portfolio XIRR since inception: {xirr_inception}%. Your best and worst decisions by XIRR: {best_holding}, {worst_holding}.`,
        q:{ q:`You invested ₹1L/year for 3 years; portfolio is now ₹3.6L. Why is "20% total return" misleading?`, opts:[`XIRR weights each rupee by its time in the market`,`20% is too low`,`total return is always right`,`fees weren't counted`], a:0, exp:`The most recent ₹1L has barely been invested. XIRR accounts for when each rupee entered, giving the true annualized figure.` } }
    ]}
  ] },
{ n:6, title:`Risk Management & Portfolio Analysis — Advanced`, level:`Advanced`, min:50, prereq:`Risk Management — Basic`,
  promise:`The quantitative layer — risk-adjusted returns, beta and correlation, stress testing, hedging, and behavioural failure modes — so you can judge a portfolio like a pro.`,
  modules:[
    { title:`Lessons`, lessons:[
      { id:`1`, t:`Risk-adjusted returns: Sharpe and friends`, min:6,
        core:`Return alone is half a number. <b>Sharpe ratio</b> = (return − risk-free rate) ÷ volatility: return per unit of bumpiness; above ~1 is respectable. <b>Sortino</b> counts only downside volatility (fairer). Two funds returning 14%: the one that did it with half the volatility is genuinely better, and Sharpe is how you see it.`,
        hook:`Sharpe ratios across your funds: {sharpe_table}. {low_sharpe_fund} delivers its returns with the roughest ride.`,
        q:{ q:`Fund A: 15% return, 22% volatility. Fund B: 13% return, 10% volatility. Risk-free 6.5%. Better Sharpe?`, opts:[`Fund B (~0.65 vs ~0.39)`,`Fund A, it returns more`,`They're equal`,`Can't tell from this`], a:0, exp:`B: (13−6.5)/10 ≈ 0.65. A: (15−6.5)/22 ≈ 0.39. Fund B earns more return per unit of risk.` } },
      { id:`2`, t:`Beta, alpha, and what your funds are really doing`, min:6,
        core:`<b>Beta</b>: sensitivity to the market (1.2 = moves ~20% more than the index, both ways). <b>Alpha</b>: return beyond what beta explains — the manager's actual value-add. Many "great" funds are just high-beta funds in a bull market: rented returns that reverse in downturns. Check whether outperformance is alpha or leverage by another name.`,
        hook:`{fund_x} has beta {beta} and 3-year alpha of {alpha}% — its outperformance is {alpha_verdict}.`,
        q:{ q:`A fund beat the index by 4% with beta 1.4 in a year the market rose 20%. Its alpha is roughly…`, opts:[`negative — beta 1.4 "owed" ~8% extra`,`+4%, clearly`,`+8%`,`zero`], a:0, exp:`Beta 1.4 in a 20% market should add ~8% over the index. Delivering only 4% extra means skill actually subtracted value.` } },
      { id:`3`, t:`Correlation: the math behind diversification`, min:6,
        core:`Diversification works only between assets that don't move together. Correlation runs −1 to +1; two Indian large-cap funds sit near +0.95 (useless pairing), equity vs gold historically near zero or negative (useful). A portfolio's risk is <i>not</i> the average of its parts. Warning: correlations rise toward +1 in crashes — which is why quality debt still matters.`,
        hook:`Correlation matrix of your holdings: {corr_summary}. Your most redundant pair: {redundant_pair} at +{corr_value}.`,
        q:{ q:`Adding an asset with −0.2 correlation and decent returns to an all-equity portfolio makes total portfolio risk…`, opts:[`fall — more than the asset's own riskiness suggests`,`rise sharply`,`stay exactly the same`,`double`], a:0, exp:`Low or negative correlation is what makes the whole calmer than its parts — total risk drops even when the new asset is itself volatile.` } },
      { id:`4`, t:`Stress testing and scenario analysis`, min:6,
        core:`Replay history against today's portfolio: 2008 (−55% equity), 2013 taper (rupee, rates), 2020 (−38% in a month, fast recovery). Then invent scenarios: "equity −40% and I lose my job the same quarter." The output isn't prediction — it's checking whether the plan survives without <b>forced selling</b>. If it doesn't, fix the allocation now, cheaply, instead of later, expensively.`,
        hook:`Stress test: in a 2008 replay your portfolio falls to ₹{stress_value}; your emergency fund covers {ef_months} months alongside it.`,
        q:{ q:`The purpose of a stress test is…`, opts:[`to verify the plan survives bad scenarios without forced selling`,`to predict the next crash`,`to time the market`,`to pick the best fund`], a:0, exp:`Stress tests check survivability, not the future. If the plan forces a sale in the scenario, you fix the allocation now.` } },
      { id:`5`, t:`Factor exposure: what you own underneath`, min:6,
        core:`Portfolios have hidden tilts — <b>size</b> (small vs large), <b>value vs growth</b>, <b>quality</b>, <b>momentum</b>. Factor lenses explain behaviour: a "diversified" set of funds may all tilt small-cap growth, so everything falls together. Factor index funds (momentum, low-vol, quality) let you <i>choose</i> tilts deliberately instead of accumulating them accidentally.`,
        hook:`Factor scan: your equity tilts {factor_tilts} vs the broad market.`,
        q:{ q:`Five funds from five AMCs, all overweight small-cap growth stocks, give you…`, opts:[`one concentrated factor bet dressed as diversification`,`true diversification`,`lower risk than one fund`,`a hedged portfolio`], a:0, exp:`Different AMCs, same underlying tilt. It's one factor bet in five wrappers — they'll all fall together.` } },
      { id:`6`, t:`Hedging basics: insurance, not alchemy`, min:6,
        core:`Ways to cut downside: raise the debt/gold sleeve (simplest, usually best), buy protective puts on index exposure (real insurance, real premium cost — a drag most long-term investors shouldn't pay continuously), or simply size equity to what you can hold through a crash. For most people the honest hedge is <b>allocation, not derivatives</b>.`,
        hook:``,
        q:{ q:`For a 15-year goal, the most cost-effective "hedge" against crashes is usually…`, opts:[`an allocation you can hold through them`,`permanent put-buying`,`daily trading`,`shorting the index`], a:0, exp:`Continuous put-buying costs more than it saves over long horizons. The cheapest hedge is an allocation you won't abandon.` } },
      { id:`7`, t:`Behavioural risk: the manager in the mirror`, min:5,
        core:`The five costliest biases, with antidotes: <b>loss aversion</b> (losses hurt ~2×; judge the portfolio, not each position), <b>recency</b> (use 10-year data), <b>overconfidence</b> (track every decision's outcome), <b>herding</b> (your written IPS), <b>anchoring</b> to buy price ("would you buy it today at this price?"). DALBAR-style studies repeatedly find investors earn several percent <i>less</i> than the funds they own — timing, not products, is the leak.`,
        hook:`Your history: you paused SIPs in {pause_month} after a {dip_pct}% dip — that pause cost roughly ₹{pause_cost} at today's NAVs.`,
        q:{ q:`The average fund investor underperforms their own fund mainly because of…`, opts:[`timing — buying after rallies and selling after falls`,`high expense ratios`,`bad fund selection`,`taxes`], a:0, exp:`The gap is behavioural: investors buy high after rallies and sell low after falls. Timing, not the product, is the leak.` } },
      { id:`8`, t:`The annual portfolio review, professionalized`, min:5,
        core:`A once-a-year, one-hour discipline: XIRR vs blended benchmark → allocation drift vs IPS → concentration & overlap scan → Sharpe/alpha check on each active fund (3-year view) → tax-loss harvesting scan → update goals. Everything else during the year is monitoring, not meddling — the review is scheduled <i>so that</i> you don't tinker weekly.`,
        hook:`Your next scheduled review: {review_date}. The copilot pre-fills all six checks the night before.`,
        q:{ q:`Checking your portfolio daily most reliably increases…`, opts:[`anxiety and trading, not returns`,`your long-term returns`,`your Sharpe ratio`,`your diversification`], a:0, exp:`Daily checking drives reaction and over-trading. Scheduled reviews beat constant monitoring for both returns and peace of mind.` } }
    ]}
  ] },
{ n:7, title:`How to Rebalance the Portfolio`, level:`Intermediate`, min:30, prereq:`Risk Management — Basic`,
  promise:`Rebalancing is the only mechanism that systematically sells high and buys low without forecasting. Learn when to do it, how to do it tax-efficiently, and when not to.`,
  modules:[
    { title:`Lessons`, lessons:[
      { id:`1`, t:`Why portfolios drift and why it matters`, min:4,
        core:`You built 60/40; a bull market silently makes it 75/25 — you now carry far more risk than you chose, at exactly the moment markets are expensive. Drift is compounding's side effect: your risk level is a garden, not a statue. Rebalancing restores the <b>chosen</b> risk, and mechanically forces sell-high/buy-low.`,
        hook:`You set {target_split}; drift has taken you to {current_split} — your portfolio is {drift_direction} riskier than you decided.`,
        q:{ q:`A 60/40 portfolio drifting to 75/25 in a bull market means your risk is highest…`, opts:[`exactly when the market is most expensive`,`when the market is cheapest`,`only in a crash`,`never — it's safer now`], a:0, exp:`Drift loads more equity precisely after prices have run up — the worst possible combination of high risk and high valuations.` } },
      { id:`2`, t:`Calendar vs threshold triggers`, min:5,
        core:`Two workable rules: <b>calendar</b> (rebalance annually — simple, tax-friendly, good enough) or <b>threshold</b> (act when any asset drifts ±5 percentage points from target — more responsive, more transactions). A popular hybrid: check quarterly, act only if the 5% band is breached. What doesn't work: rebalancing on feelings or headlines.`,
        hook:`Under a ±5% band rule, your portfolio breached its band on {breach_date}. Under annual-only, your next action date is {annual_date}.`,
        q:{ q:`The main advantage of a written trigger rule over judgment is…`, opts:[`it removes emotion — you act on drift, not fear or greed`,`it guarantees higher returns`,`it avoids all taxes`,`it needs no monitoring`], a:0, exp:`A written rule makes you act on measured drift rather than on how the market feels that week.` } },
      { id:`3`, t:`Rebalance with new money first`, min:4,
        core:`Selling triggers taxes and exit loads; steering <b>fresh</b> money doesn't. First lever: redirect SIPs toward the underweight asset until balance returns. For most accumulating investors with ongoing SIPs, this alone handles normal drift — sell-based rebalancing becomes rare, reserved for big moves or large portfolios.`,
        hook:`Redirecting your ₹{sip_total}/month SIP entirely to {underweight_asset} restores your target in ~{months_to_balance} months — zero tax.`,
        q:{ q:`The cheapest rebalancing lever is…`, opts:[`directing new SIP money to the underweight asset`,`selling the overweight asset`,`stopping all SIPs`,`switching to cash`], a:0, exp:`Redirecting fresh contributions involves no sale — no tax, no exit load. It's the cheapest way to correct normal drift.` } },
      { id:`4`, t:`Tax-aware selling, when you must`, min:5,
        core:`When selling is unavoidable, order of operations: prefer units held >12 months (LTCG 12.5% vs STCG 20% for equity); use the <b>₹1.25L annual LTCG exemption</b> as a free rebalancing allowance every year; check exit-load clocks; sell the highest-cost lots where allowed. A rebalance planned in February can often split across two financial years to use two exemptions.`,
        hook:`You've used ₹{ltcg_used} of this year's ₹1.25L LTCG exemption — ₹{ltcg_room} of equity can be rebalanced tax-free before March 31.`,
        q:{ q:`Rebalancing ₹2L of equity gains in late March vs splitting across March and April…`, opts:[`splitting can use two years' ₹1.25L exemptions`,`makes no difference`,`is always taxed more`,`is not allowed`], a:0, exp:`Two financial years means two ₹1.25L exemptions — potentially zero tax instead of tax on the excess.` } },
      { id:`5`, t:`Rebalancing between funds, not just assets`, min:4,
        core:`Same discipline applies within equity: your small-cap sleeve doubling from 15% to 30% of equity is drift too, and small-cap booms are historically where the next crash concentrates. It's also the moment to act on overlap findings: consolidation is best executed as part of a planned, tax-checked rebalance rather than ad hoc.`,
        hook:`Within equity, your small-cap sleeve has grown to {smallcap_pct}% against a {smallcap_target}% target.`,
        q:{ q:`Your small-cap allocation doubled by outperforming. Rebalancing it now feels wrong because…`, opts:[`recency bias — trimming winners always feels wrong`,`it is actually wrong`,`small-caps never fall`,`the rule doesn't apply within equity`], a:0, exp:`Trimming a winner feels bad, which is exactly why the written rule — not the feeling — should decide.` } },
      { id:`6`, t:`When not to rebalance`, min:4,
        core:`Skip it when: drift is within your band (transaction costs and taxes exceed the benefit), the "drift" is one week of volatility rather than a level change, or a life change means the <b>target itself</b> should change (new goal, nearing retirement) — that's re-planning, not rebalancing. Rebalancing is maintenance; changing the destination is a different decision, made calmly with the IPS open.`,
        hook:``,
        q:{ q:`Your allocation moved 2% off target this month. The rule-following action is…`, opts:[`nothing — inside the band, doing nothing is disciplined`,`sell immediately`,`double your SIP`,`switch everything to debt`], a:0, exp:`A 2% move is inside a ±5% band. Acting on it would cost more in taxes and fees than it's worth — discipline is doing nothing.` } }
    ]}
  ] },
{ n:8, title:`Taxation & Compliance for Stocks & MFs`, level:`Intermediate`, min:50, prereq:`MF Starter Kit`,
  promise:`Know exactly what you'll owe before you sell, harvest what the law lets you harvest, and file without fear. Rates as of FY 2025–26 / AY 2026–27.`,
  modules:[
    { title:`Lessons`, lessons:[
      { id:`1`, t:`The capital gains map`, min:5,
        core:`Profit on selling an investment = capital gain; the tax depends on <b>what</b> and <b>how long</b>. For listed equity shares and equity funds (≥65% Indian equity): ≤12 months = short-term, >12 months = long-term. <b>STCG: 20%</b> (Sec 111A). <b>LTCG: 12.5%</b> above a <b>₹1.25 lakh</b> annual exemption (Sec 112A), no indexation. Memorize those three numbers — 12 months, 20%, 12.5% above ₹1.25L.`,
        hook:`Your unrealized gains today: ₹{stcg_unrealized} short-term, ₹{ltcg_unrealized} long-term. Selling everything now would cost ≈ ₹{tax_if_sold}.`,
        q:{ q:`You sell equity fund units after 14 months with ₹2L gain (no other LTCG). Tax?`, opts:[`₹9,375 — 12.5% of ₹75,000`,`₹25,000`,`₹0`,`₹40,000`], a:0, exp:`Held >12 months so LTCG. First ₹1.25L is exempt; 12.5% of the remaining ₹75,000 = ₹9,375.` } },
      { id:`2`, t:`Debt, gold, and international: the other rulebook`, min:5,
        core:`Debt funds bought <b>on or after 1 Apr 2023</b>: all gains taxed at your <b>slab rate regardless of holding period</b> — no LTCG benefit, no indexation. Units bought before that date are grandfathered. Gold and most international funds have their own evolving treatment. The meta-lesson: <i>non-equity taxation changes often — check current rules before selling, not after.</i>`,
        hook:`Your debt fund units: ₹{pre2023_amt} bought pre-Apr-2023 (grandfathered), ₹{post2023_amt} after (slab-taxed at your {slab}%).`,
        q:{ q:`A debt fund bought in 2024 and held 5 years is taxed at…`, opts:[`your slab rate`,`12.5% LTCG`,`20% STCG`,`0% after 3 years`], a:0, exp:`Post-1-Apr-2023 debt fund gains get no long-term concession — they're taxed at your slab rate regardless of holding period.` } },
      { id:`3`, t:`The ₹1.25 lakh gift: LTCG harvesting`, min:5,
        core:`The exemption <b>resets every financial year</b> — unused, it's wasted. Harvesting: sell long-term equity units with up to ₹1.25L of gains, buy back promptly (mind exit loads and a few days of market risk), and your cost basis steps up — future taxable gains shrink, at a tax cost of zero. Done annually for 15 years, this can legally erase lakhs of eventual tax.`,
        hook:`You have ₹{harvest_room} of unused exemption and ₹{eligible_ltcg} of eligible long-term gains — the copilot has a harvest plan ready before March 31.`,
        q:{ q:`Why sell and immediately rebuy units showing ₹1.2L long-term gain in March?`, opts:[`To use the ₹1.25L exemption and reset the cost basis higher`,`To book a loss`,`To avoid the 3-year lock`,`To change fund houses`], a:0, exp:`It realizes gains tax-free within the exemption and steps up your cost basis — legally shrinking future tax to nothing.` } },
      { id:`4`, t:`Losses are assets: set-off and carry-forward`, min:5,
        core:`<b>Short-term capital losses</b> set off against both STCG and LTCG; <b>long-term losses</b> only against LTCG. Unused losses carry forward <b>8 assessment years</b> — but <i>only if you file your ITR by the due date</i>. Tax-loss harvesting: realize losses on genuine duds to neutralize gains elsewhere. Caution: don't sell a good investment just to book a loss — the tax tail shouldn't wag the portfolio dog.`,
        hook:`You're carrying ₹{loss_cf} of losses from {loss_year}, and hold ₹{unrealized_loss} of unrealized losses that could offset this year's ₹{gains} of gains.`,
        q:{ q:`₹80k STCG this year, and a fund at ₹60k short-term loss you already wanted to exit. Selling it before March 31…`, opts:[`cuts taxable STCG to ₹20k, saving ₹12k at 20%`,`does nothing for tax`,`increases your tax`,`is not allowed`], a:0, exp:`The ₹60k short-term loss sets off the STCG, leaving ₹20k taxable — a ₹12k saving at the 20% STCG rate.` } },
      { id:`5`, t:`SIPs, switches, and other quiet tax events`, min:5,
        core:`Three traps: (1) <b>Each SIP installment is its own lot</b> with its own 12-month clock; redeeming a 3-year-old folio still triggers STCG on recent installments (FIFO applies). (2) <b>A switch is a sale</b> — fund A→B, regular→direct, growth→IDCW all trigger capital gains even though no cash reached your bank. (3) <b>IDCW (dividend) payouts</b> are taxed at your slab, which is why growth option usually wins above the lowest slabs.`,
        hook:`If you redeem {fund_x} fully today, {recent_units_pct}% of units are still short-term — FIFO would tax ₹{stcg_portion} at 20%.`,
        q:{ q:`Switching from a regular plan to the direct plan of the same fund is…`, opts:[`a taxable redemption — capital gains apply`,`tax-free, it's the same fund`,`only taxed after 3 years`,`a dividend event`], a:0, exp:`A switch is a redemption plus a fresh purchase. Capital gains apply even though the money never left the fund house.` } },
      { id:`6`, t:`ELSS and the two-regime question`, min:5,
        core:`ELSS gives an <b>80C deduction up to ₹1.5L — but only under the old tax regime</b>; under the new (default) regime there's no 80C, so ELSS is just an equity fund with a 3-year lock. Decide regime first (a whole-income comparison), then decide whether ELSS earns its lock-in. Note: STT is charged on equity transactions automatically and isn't deductible against 111A/112A gains.`,
        hook:`Based on your income structure, the copilot estimates the {better_regime} regime saves you ₹{regime_delta}/year — which {elss_verdict} your ELSS SIP.`,
        q:{ q:`Under the new tax regime, investing in ELSS gets you…`, opts:[`no 80C deduction — just an equity fund with a 3-year lock`,`a full ₹1.5L deduction`,`tax-free returns`,`a shorter lock-in`], a:0, exp:`80C only exists under the old regime. Under the new regime ELSS loses its deduction and is just a locked equity fund.` } },
      { id:`7`, t:`Trading income is not capital gains`, min:4,
        core:`Intraday equity = <b>speculative business income</b> (slab rates); F&O = <b>non-speculative business income</b> (slab rates, possible audit at scale); delivery-based investing = capital gains. These live in different ITR schedules and can't be mixed or netted casually. Dabble in F&O "on the side" and you may have converted a simple ITR-2 into an ITR-3 with books of account.`,
        hook:``,
        q:{ q:`Your ₹40k intraday profit is taxed…`, opts:[`at your slab rate as speculative business income`,`at 20% STCG`,`at 12.5% LTCG`,`tax-free under ₹1L`], a:0, exp:`Intraday equity is speculative business income, taxed at your slab rate — not at the 20% STCG rate for delivery trades.` } },
      { id:`8`, t:`Filing: which ITR, what documents, what deadlines`, min:5,
        core:`Capital gains → <b>ITR-2</b> (small 112A LTCG within the exemption can fit ITR-1); any intraday/F&O → <b>ITR-3</b>. Gather: broker Tax P&L, CAMS/KFintech capital gains statements, AIS/Form 26AS (the department already sees your trades — mismatches trigger notices). If total tax due exceeds ₹10,000, <b>advance tax</b> applies. File by the due date or lose loss carry-forward.`,
        hook:`The copilot has assembled your capital gains statement from {rta_sources} — {mismatch_count} entries differ from your AIS; resolve before filing.`,
        q:{ q:`The department's AIS already shows your MF redemptions. Filing an ITR that omits them…`, opts:[`invites an automated mismatch notice — reconcile AIS first`,`is fine, they won't notice`,`reduces your tax`,`is required by law`], a:0, exp:`AIS is pre-populated from the same data. Omissions surface as automated mismatch notices — reconcile before filing, not after.` } },
      { id:`9`, t:`Compliance hygiene: nominee, KYC, and the paper trail`, min:4,
        core:`The unglamorous list that saves families and audits: <b>nominee</b> registered on every folio and demat account (now mandated); <b>KYC status "validated"</b> (stale KYC freezes transactions); email/mobile consistent across folios; annual download of NSDL/CDSL <b>CAS</b> as your master record; clear records for inherited investments (inheritance itself isn't taxed; the <i>sale</i> later is, using the original owner's cost and date).`,
        hook:`Compliance scan: nominee missing on {no_nominee_count} folios; KYC status {kyc_status}; last CAS on record: {cas_date}.`,
        q:{ q:`Your late parent's mutual fund units transferred to you are taxed…`, opts:[`only when you sell — using their original cost and date`,`at transfer, as your income`,`never`,`at a flat 30%`], a:0, exp:`Inheritance itself isn't taxed. The gain is computed at sale using the original owner's purchase cost and date.` } }
    ]}
  ] },
/*COURSES*/
];
