logging:
  receivers:
    docker_json_logs:
      type: files
      include_paths:
        - /var/lib/docker/containers/*/*.log
  processors:
    parse_docker_wrapper:
      type: parse_json
      field: message
    parse_app_json:
      type: parse_json
      field: log
    promote_severity:
      type: modify_fields
      fields:
        severity:
          copy_from: jsonPayload.severity
  service:
    pipelines:
      docker_pipeline:
        receivers: [docker_json_logs]
        processors: [parse_docker_wrapper, parse_app_json, promote_severity]
