import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardLabel } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { MetricCard } from "@/components/shared/MetricCard";
import { RiskMeter } from "@/components/charts/RiskMeter";
import { formatINR, formatPct, formatDate } from "@/lib/formatters";
export function FundDetails({ holding: h }) {
    const r = h.returns;
    return (_jsxs("div", { className: "px-6 py-8 lg:px-10 lg:py-10 max-w-[1080px] mx-auto w-full", children: [_jsxs("div", { className: "flex items-baseline gap-3", children: [_jsx("span", { className: "font-mono text-[11px] uppercase tracking-[.18em] text-ink-3", children: "Fund" }), _jsx(Badge, { tone: "outline", children: h.fund.category.replace("-", " ").toUpperCase() })] }), _jsx("h1", { className: "font-display text-3xl sm:text-4xl tracking-tightish leading-[1.05] mt-1.5", children: h.fund.name }), _jsxs("div", { className: "font-mono text-[11px] text-ink-3 mt-2", children: [h.fund.amc, " \u00B7 ISIN ", h.fund.isin, " \u00B7 AMFI ", h.fund.amfiCode] }), _jsxs("div", { className: "grid grid-cols-2 lg:grid-cols-4 gap-3 mt-7", children: [_jsx(MetricCard, { label: "Your value", value: formatINR(h.marketValue, { compact: true }), subtext: `${h.units.toFixed(2)} units` }), _jsx(MetricCard, { label: "Invested", value: formatINR(h.costBasis, { compact: true }), subtext: `since ${formatDate(h.startedOn)}` }), _jsx(MetricCard, { label: "Returns", value: `+${formatINR(h.unrealizedPnl, { compact: true })}`, subtext: formatPct(h.unrealizedPnlPct, { signed: true }), tone: "pos" }), _jsx(MetricCard, { label: "NAV", value: `₹${(h.fund.nav / 100).toFixed(2)}`, subtext: `as of ${h.fund.navAsOf}` })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-[1fr_280px] gap-5 mt-5", children: [_jsxs(Card, { className: "p-6", children: [_jsx(CardLabel, { children: "Returns \u00B7 annualised" }), _jsx("div", { className: "grid grid-cols-3 sm:grid-cols-6 gap-4 mt-5", children: [
                                    ["1M", r.m1], ["3M", r.m3], ["6M", r.m6], ["1Y", r.y1], ["3Y", r.y3], ["5Y", r.y5],
                                ].map(([l, v]) => (_jsxs("div", { children: [_jsx("div", { className: "font-mono text-[10px] uppercase tracking-[.1em] text-ink-3", children: l }), _jsx("div", { className: `font-display text-2xl mt-1 tracking-tightish ${v >= 0 ? "text-pos" : "text-neg"}`, children: formatPct(v, { signed: true }) })] }, l))) }), _jsxs("div", { className: "mt-4 pt-4 border-t border-hairline font-mono text-[11px] text-ink-3 tracking-[.04em]", children: ["CAGR \u00B7 ", formatPct(r.cagr, { signed: true }), " since inception"] })] }), _jsxs(Card, { className: "p-6", children: [_jsx(CardLabel, { children: "Risk" }), _jsx(RiskMeter, { level: h.fund.riskometer, className: "mt-4", label: "Riskometer" }), _jsxs("div", { className: "mt-4 pt-4 border-t border-hairline", children: [_jsx(CardLabel, { children: "Expense ratio" }), _jsxs("div", { className: "font-display text-xl mt-1", children: [(h.fund.expenseRatio * 100).toFixed(2), "%"] }), _jsx("div", { className: "font-mono text-[10.5px] text-ink-3 mt-1", children: "Annual \u00B7 direct plan" })] })] })] }), h.sipMonthly && (_jsxs(Card, { className: "mt-5 p-6", children: [_jsx(CardLabel, { children: "Active SIP" }), _jsxs("div", { className: "flex items-baseline gap-3 mt-2", children: [_jsxs("span", { className: "font-display text-2xl tracking-tightish num", children: [formatINR(h.sipMonthly, { compact: true }), " / month"] }), _jsxs("span", { className: "font-mono text-[11px] text-ink-3", children: ["since ", formatDate(h.startedOn)] })] })] }))] }));
}
