#!/usr/bin/env bash
# bootstrap-staging.sh — one-time setup for the staging stack on nivesh-app-vm.
#
# Run as root (or via sudo) on the VM. Idempotent: safe to re-run.
#   sudo bash /opt/nivesh-staging/repo/deploy/nivesh-staging/bootstrap-staging.sh
#
# Creates:
#   - /opt/nivesh-staging/{data/{postgres,mongo,redis},logs}
#   - /opt/nivesh-staging/.env.staging   (with freshly-generated secrets)
# Verifies:
#   - Docker is installed and running
#   - Required ports (5532, 27117, 6479, 8443) are free on the relevant binds

set -euo pipefail

STAGING_ROOT="/opt/nivesh-staging"
ENV_FILE="${STAGING_ROOT}/.env.staging"

log() { echo "[bootstrap-staging] $*"; }
fail() { echo "[bootstrap-staging] FATAL: $*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || fail "Run as root (sudo)."

log "Ensuring directories exist under ${STAGING_ROOT}/"
mkdir -p \
    "${STAGING_ROOT}/data/postgres" \
    "${STAGING_ROOT}/data/mongo" \
    "${STAGING_ROOT}/data/redis" \
    "${STAGING_ROOT}/logs"
chmod 750 "${STAGING_ROOT}"

log "Checking docker presence..."
command -v docker >/dev/null || fail "docker not found on PATH"
docker info >/dev/null 2>&1 || fail "docker daemon not reachable"

if [[ -f "${ENV_FILE}" ]]; then
    log ".env.staging already exists; leaving as-is (rotate manually if needed)."
else
    log "Generating ${ENV_FILE} with fresh random secrets..."
    pg_pass=$(openssl rand -hex 24)
    mongo_pass=$(openssl rand -hex 24)
    redis_pass=$(openssl rand -hex 24)
    cat >"${ENV_FILE}" <<EOF
# Auto-generated by bootstrap-staging.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Rotate by deleting this file and re-running bootstrap-staging.sh.

PI_POSTGRES_USER=pi_staging
PI_POSTGRES_PASSWORD=${pg_pass}
PI_POSTGRES_DB=portfolio_ingestion

PI_MONGO_USER=pi_staging
PI_MONGO_PASSWORD=${mongo_pass}
PI_MONGO_DB=portfolio_ingestion

PI_REDIS_PASSWORD=${redis_pass}

PI_NGINX_BIND_ADDR=127.0.0.1
PI_NGINX_PORT=8443
EOF
    chmod 600 "${ENV_FILE}"
    log "Wrote ${ENV_FILE} (mode 600)."
fi

# Conflict checks: each host port must be free on its intended bind.
check_port_free() {
    local bind="$1" port="$2"
    if ss -ltn "src ${bind}:${port}" 2>/dev/null | grep -q LISTEN; then
        fail "Port ${bind}:${port} is already in use; cannot bring up staging."
    fi
}
# Re-read the bind from the env file (in case the operator changed it)
# shellcheck disable=SC1090
source "${ENV_FILE}"
PI_NGINX_BIND_ADDR="${PI_NGINX_BIND_ADDR:-127.0.0.1}"
PI_NGINX_PORT="${PI_NGINX_PORT:-8443}"

check_port_free "127.0.0.1" 5532
check_port_free "127.0.0.1" 27117
check_port_free "127.0.0.1" 6479
check_port_free "${PI_NGINX_BIND_ADDR}" "${PI_NGINX_PORT}"

log "Bootstrap OK. Next: run redeploy-staging.sh to build + start the stack."
