import { jsx as _jsx } from "react/jsx-runtime";
import * as React from "react";
import { cn } from "@/lib/utils";
export const Card = React.forwardRef(({ className, ...props }, ref) => (_jsx("div", { ref: ref, className: cn("rounded-lg bg-surface-1 border-hairline border shadow-card", className), ...props })));
Card.displayName = "Card";
export const CardHeader = ({ className, ...props }) => (_jsx("div", { className: cn("px-6 pt-6 pb-3", className), ...props }));
export const CardTitle = ({ className, ...props }) => (_jsx("h3", { className: cn("font-display text-2xl tracking-tightish", className), ...props }));
export const CardDescription = ({ className, ...props }) => (_jsx("p", { className: cn("text-sm text-ink-2 mt-1", className), ...props }));
export const CardContent = ({ className, ...props }) => (_jsx("div", { className: cn("px-6 pb-6", className), ...props }));
export const CardFooter = ({ className, ...props }) => (_jsx("div", { className: cn("px-6 pb-6 pt-3 flex items-center gap-2", className), ...props }));
export const CardLabel = ({ className, ...props }) => (_jsx("div", { className: cn("font-mono text-[11px] uppercase tracking-[.14em] text-ink-3", className), ...props }));
