import { jsx as _jsx } from "react/jsx-runtime";
import * as React from "react";
import * as TabsPrimitive from "@radix-ui/react-tabs";
import { cn } from "@/lib/utils";
export const Tabs = TabsPrimitive.Root;
export const TabsList = React.forwardRef(({ className, ...props }, ref) => (_jsx(TabsPrimitive.List, { ref: ref, className: cn("flex border-b border-hairline gap-1", className), ...props })));
TabsList.displayName = TabsPrimitive.List.displayName;
export const TabsTrigger = React.forwardRef(({ className, ...props }, ref) => (_jsx(TabsPrimitive.Trigger, { ref: ref, className: cn("inline-flex items-center px-4 py-3 text-sm text-ink-3 -mb-px border-b-2 border-transparent", "data-[state=active]:text-ink data-[state=active]:border-accent data-[state=active]:font-medium", "hover:text-ink-2", className), ...props })));
TabsTrigger.displayName = TabsPrimitive.Trigger.displayName;
export const TabsContent = React.forwardRef(({ className, ...props }, ref) => (_jsx(TabsPrimitive.Content, { ref: ref, className: cn("pt-6 focus-visible:outline-none", className), ...props })));
TabsContent.displayName = TabsPrimitive.Content.displayName;
