"""Factory for placeholder broker adapters.

All 19 Nivesh-listed brokers register in `services.brokers.registry`,
but only the priority ones have full SDK or HTTP-client adapters
shipped initially. The rest get a stub from this module so:

  * `/api/broker/native/supported` lists every broker uniformly.
  * Operators can configure per-broker secrets in advance.
  * Clicking an unimplemented broker returns a clean
    "implementation pending" error rather than a stack trace.

Each stub is generated by `make_stub(slug, display, auth_style)` and
registers itself on import.
"""
from __future__ import annotations

from typing import List

from . import registry
from .base import AccessToken, Funds, Holding, Position


class _NotImplementedYet(RuntimeError):
    pass


def make_stub(slug: str, display: str, auth_style: str = "form"):
    """Return a Broker-protocol-compliant stub module that registers
    itself for `slug` and raises a clear error on any call.
    """
    msg = (
        f"Native broker adapter for {display!r} (slug={slug!r}) is not yet "
        "implemented. The OpenAlgo-based path remains available — set the "
        "broker's API key via the admin secrets and use /api/broker/connect-hosted "
        "instead, or wait for a native adapter."
    )

    def _auth_url(*, state: str, redirect_uri: str) -> str:
        raise _NotImplementedYet(msg)

    async def _exchange_code(*, code: str, state: str, redirect_uri: str) -> AccessToken:
        raise _NotImplementedYet(msg)

    async def _fetch_holdings(token: AccessToken) -> List[Holding]:
        raise _NotImplementedYet(msg)

    async def _fetch_positions(token: AccessToken) -> List[Position]:
        raise _NotImplementedYet(msg)

    async def _fetch_funds(token: AccessToken) -> Funds:
        raise _NotImplementedYet(msg)

    class _Stub:
        SLUG = slug
        DISPLAY = display
        AUTH_STYLE = auth_style
        auth_url = staticmethod(_auth_url)
        exchange_code = staticmethod(_exchange_code)
        fetch_holdings = staticmethod(_fetch_holdings)
        fetch_positions = staticmethod(_fetch_positions)
        fetch_funds = staticmethod(_fetch_funds)
        IMPLEMENTED = False  # registry can surface this on the dropdown

    registry.register(_Stub())
    return _Stub


# ── Self-register the not-yet-implemented brokers ────────────────────────
# Order: alphabetical by display name. When implementing a new adapter,
# delete its entry here and add a real module under `services/brokers/`.
make_stub("definedge", "Definedge", "form")
make_stub("flattrade", "Flattrade", "form")
make_stub("groww", "Groww", "form")
make_stub("iifl", "IIFL", "oauth")
make_stub("iiflcapital", "IIFL Capital", "oauth")
make_stub("indmoney", "INDmoney", "oauth")
make_stub("kotak", "Kotak Neo", "form")
make_stub("motilal", "Motilal Oswal", "form")
make_stub("mstock", "m.Stock", "form")
make_stub("paytm", "Paytm Money", "oauth")
make_stub("samco", "Samco", "form")
make_stub("shoonya", "Shoonya", "form")
make_stub("tradejini", "Tradejini", "form")
