"""Writes backend/services/move_odds_setup_diagnostics.json — the Move odds page's Diagnostics section — from
entry_setups_result.json (the pre-registered backtest), per the owner's decision of 2026-09-17 ~12:10 IST:
A and B "Setup detected — not validated", C and D "Research only; insufficient sample". Numbers are copied, never
recomputed or rounded here; the order is A, B, C, D whatever the results.

    python docs/ai_research/tpd3/entry_setups/make_page_diagnostics.py            # writes the snapshot
    python docs/ai_research/tpd3/entry_setups/make_page_diagnostics.py --check    # exit 1 if the snapshot differs
"""
import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
RESULT = HERE / "entry_setups_result.json"
SNAPSHOT = HERE.parents[3] / "backend" / "services" / "move_odds_setup_diagnostics.json"

SETUPS = [("A", "a", "Confirmed breakout", "not_validated"),
          ("B", "b", "Pullback continuation", "not_validated"),
          ("C", "c", "Results-day momentum", "research_only_insufficient_sample"),
          ("D", "d", "Volatility expansion", "research_only_insufficient_sample")]
LABEL = {"not_validated": ("Not validated", "Setup detected — not validated"),
         "research_only_insufficient_sample": ("Research only; insufficient sample", "Research only; insufficient sample")}
NOT_VALIDATED_TEXT = ("This setup detected a historical price pattern but did not demonstrate positive net expectancy or improvement "
                      "over the eligible-stock baseline in the tested period. It must not be interpreted as an entry recommendation.")


def _trade(result: dict, key: str, trade: str) -> dict:
    s = result["setups"][f"{key}_{trade}"]
    v = result["verdicts"][f"{key}_{trade}"]
    ci = s.get("ci95") or [None, None]
    return {"trade": trade, "trades": s["trades"], "mean_net": s.get("mean_net"),
            "ci95": ci if None not in ci else None,
            "baseline_mean_net": result["baseline"][trade]["mean_net"],
            "half1_mean_net": s["half1"].get("mean_net"), "half2_mean_net": s["half2"].get("mean_net"),
            "validation": "passed" if v["verdict"] == "validated" else "failed",
            "failed_checks": [c for c, ok in v["checks"].items() if not ok]}


def build(result_bytes: bytes) -> dict:
    result = json.loads(result_bytes)
    setups = []
    for sid, key, name, status in SETUPS:
        trades = [_trade(result, key, t) for t in ("5%", "10%")]
        if any(t["validation"] == "passed" for t in trades):
            raise SystemExit(f"setup {sid} has a validated trade; the owner's page decision assumed none — stop and ask")
        if status == "not_validated":
            text = NOT_VALIDATED_TEXT
        else:
            n5, n10 = trades[0]["trades"], trades[1]["trades"]
            text = (f"Only {n5:,} and {n10:,} trades passed the rules for the 5% and 10% versions, below the 200 required, and those "
                    "trades lost money on average. It is kept for research only and must not be interpreted as an entry recommendation.")
        chip, headline = LABEL[status]
        setups.append({"id": sid, "name": name, "status": status, "status_label": chip, "headline": headline,
                       "research_status": "Research status · Not a trading signal", "explanation": text, "trades": trades})
    verdicts = result["verdicts"].values()
    return {
        "_comment": "Generated by docs/ai_research/tpd3/entry_setups/make_page_diagnostics.py from entry_setups_result.json. Do not edit by hand.",
        "source": "docs/ai_research/tpd3/entry_setups/entry_setups_result.json",
        "source_sha256": hashlib.sha256(result_bytes).hexdigest(),
        "decided": "2026-09-17",
        "study": {
            "title": "Entry setups research",
            "first_signal_day": result["signal_days"][0], "last_signal_day": result["signal_days"][1],
            "universe": "About 1,000 most-traded NSE stocks, chosen day by day from past turnover",
            "cost_round_trip": result["cost_round_trip"],
            "exits": "Each simulated trade closed at a 5% or 10% gain, at a pre-set loss limit, or at the fifth session's close",
            "rule": ("Validated only with at least 200 trades, a positive average net result whose 95% confidence interval is above zero, "
                     "a better average than the baseline, and a positive average in both halves of the period"),
            "baseline": "Every eligible stock-day, entered at the next session's open with the same exits and costs",
            "tested": len(result["verdicts"]),
            "validated": sum(1 for v in verdicts if v["verdict"] == "validated"),
        },
        "setups": setups,
    }


def main(argv: list[str]) -> int:
    rb = RESULT.read_bytes()
    text = json.dumps(build(rb), indent=2, ensure_ascii=False) + "\n"
    if "--check" in argv:
        same = SNAPSHOT.exists() and SNAPSHOT.read_text() == text
        print("snapshot matches" if same else "snapshot DIFFERS from entry_setups_result.json")
        return 0 if same else 1
    SNAPSHOT.write_text(text)
    print(f"wrote {SNAPSHOT} (source sha256 {hashlib.sha256(rb).hexdigest()[:12]})")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
