#!/bin/bash
#
# Auto-recovery script for PostgreSQL + Redis on container restart
# This script handles the known issue where Kubernetes container restarts
# wipe system users and packages.
#
# Usage: Run this automatically on container startup or manually when services are down
#

set -e

echo "🔧 Nivesh.AI Datastore Auto-Recovery Script"
echo "============================================"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}✓${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}⚠${NC} $1"
}

log_error() {
    echo -e "${RED}✗${NC} $1"
}

# Step 1: Create system users if missing
echo ""
echo "📋 Step 1: Checking system users..."
if ! id postgres &>/dev/null; then
    log_warn "Creating postgres user..."
    sudo useradd -r -s /bin/false postgres 2>/dev/null || true
    log_info "Postgres user created"
else
    log_info "Postgres user exists"
fi

if ! id redis &>/dev/null; then
    log_warn "Creating redis user..."
    sudo useradd -r -s /bin/false redis 2>/dev/null || true
    log_info "Redis user created"
else
    log_info "Redis user exists"
fi

# Step 2: Install packages if missing
echo ""
echo "📦 Step 2: Checking packages..."
if ! command -v postgres &>/dev/null; then
    log_warn "PostgreSQL not found. Installing..."
    export DEBIAN_FRONTEND=noninteractive
    sudo apt-get update -qq
    sudo apt-get install -y postgresql-15 -qq > /dev/null 2>&1
    log_info "PostgreSQL 15 installed"
else
    log_info "PostgreSQL installed"
fi

if ! command -v redis-server &>/dev/null; then
    log_warn "Redis not found. Installing..."
    export DEBIAN_FRONTEND=noninteractive
    sudo apt-get update -qq
    sudo apt-get install -y redis-server -qq > /dev/null 2>&1
    log_info "Redis installed"
else
    log_info "Redis installed"
fi

# Step 3: Initialize PostgreSQL data directory
echo ""
echo "🗄️  Step 3: Initializing PostgreSQL..."
PG_DATA_DIR="/var/lib/postgresql/15/main"
if [ ! -f "$PG_DATA_DIR/PG_VERSION" ]; then
    log_warn "Initializing PostgreSQL data directory..."
    sudo mkdir -p "$PG_DATA_DIR"
    sudo chown -R postgres:postgres /var/lib/postgresql/15
    sudo -u postgres /usr/lib/postgresql/15/bin/initdb -D "$PG_DATA_DIR" > /dev/null 2>&1 || true
    log_info "PostgreSQL data directory initialized"
else
    log_info "PostgreSQL data directory exists"
fi

# Step 4: Configure PostgreSQL authentication
echo ""
echo "🔐 Step 4: Configuring PostgreSQL authentication..."
PG_HBA="/etc/postgresql/15/main/pg_hba.conf"
if [ -f "$PG_HBA" ]; then
    # Backup original
    sudo cp "$PG_HBA" "$PG_HBA.backup_$(date +%s)" 2>/dev/null || true
fi

# Create minimal pg_hba.conf with trust auth for local connections
sudo tee "$PG_HBA" > /dev/null <<EOF
# PostgreSQL Client Authentication Configuration (Auto-generated by restore script)
# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             postgres                                trust
host    all             postgres        127.0.0.1/32            trust
host    all             postgres        ::1/128                 trust
local   all             all                                     peer
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5
EOF
log_info "PostgreSQL authentication configured"

# Step 5: Configure PostgreSQL connection settings
echo ""
echo "⚙️  Step 5: Configuring PostgreSQL settings..."
PG_CONF="/etc/postgresql/15/main/postgresql.conf"
if [ -f "$PG_CONF" ]; then
    sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = 'localhost'/" "$PG_CONF" 2>/dev/null || true
    sudo sed -i "s/#port = 5432/port = 5432/" "$PG_CONF" 2>/dev/null || true
    log_info "PostgreSQL connection settings configured"
fi

# Step 6: Restart supervisor to pick up services
echo ""
echo "🔄 Step 6: Restarting services..."
if sudo service supervisor status &>/dev/null; then
    log_info "Supervisor already running"
else
    sudo service supervisor start
    sleep 2
fi

# Reload supervisor config
sudo supervisorctl reread > /dev/null 2>&1 || true
sudo supervisorctl update > /dev/null 2>&1 || true

# Restart datastores
sudo supervisorctl restart postgres redis > /dev/null 2>&1 || true
sleep 3

# Check status
PG_STATUS=$(sudo supervisorctl status postgres | awk '{print $2}')
REDIS_STATUS=$(sudo supervisorctl status redis | awk '{print $2}')

if [ "$PG_STATUS" = "RUNNING" ]; then
    log_info "PostgreSQL is RUNNING"
else
    log_error "PostgreSQL is $PG_STATUS"
fi

if [ "$REDIS_STATUS" = "RUNNING" ]; then
    log_info "Redis is RUNNING"
else
    log_error "Redis is $REDIS_STATUS"
fi

# Step 7: Create nivesh database if missing
echo ""
echo "💾 Step 7: Ensuring nivesh database exists..."
if sudo -u postgres psql -lqt | cut -d \| -f 1 | grep -qw nivesh; then
    log_info "Database 'nivesh' exists"
else
    log_warn "Creating database 'nivesh'..."
    sudo -u postgres createdb nivesh
    log_info "Database 'nivesh' created"
fi

# Step 8: Verify connectivity
echo ""
echo "🧪 Step 8: Testing connectivity..."
if sudo -u postgres psql -d nivesh -c "SELECT 1;" > /dev/null 2>&1; then
    log_info "PostgreSQL connection test: PASSED"
else
    log_error "PostgreSQL connection test: FAILED"
fi

if redis-cli ping > /dev/null 2>&1; then
    log_info "Redis connection test: PASSED"
else
    log_error "Redis connection test: FAILED"
fi

# Step 8b: Apply PG schema + restore data from MongoDB mirror
# MongoDB is persistent across forks; PG is wiped. This brings PG back to life.
echo ""
echo "🔁 Step 8b: Applying PG schema + restoring from MongoDB mirror..."
SCHEMA_FILE="/app/backend/migrations/001_phase2_mf_schema.sql"
if [ -f "$SCHEMA_FILE" ]; then
    PGPASSWORD=postgres psql -h localhost -U postgres -d nivesh -f "$SCHEMA_FILE" > /dev/null 2>&1 \
        && log_info "PG schema applied (idempotent)" \
        || log_warn "PG schema apply had issues (may already exist)"
fi
if [ -f "/app/backend/scripts/restore_pg_from_mongo.py" ]; then
    cd /app/backend && /root/.venv/bin/python -m scripts.restore_pg_from_mongo 2>&1 | tail -5 | sed 's/^/    /'
    log_info "PG data restore from Mongo mirror attempted"
else
    log_warn "restore_pg_from_mongo.py not found — skipping PG data restore"
fi

# Step 9: Restart backend to reconnect to datastores
echo ""
echo "🚀 Step 9: Restarting backend application..."
sudo supervisorctl restart backend > /dev/null 2>&1
sleep 3
BACKEND_STATUS=$(sudo supervisorctl status backend | awk '{print $2}')
if [ "$BACKEND_STATUS" = "RUNNING" ]; then
    log_info "Backend is RUNNING"
else
    log_error "Backend is $BACKEND_STATUS"
fi

# Final status
echo ""
echo "============================================"
echo "✅ Auto-recovery complete!"
echo ""
echo "Service Status:"
sudo supervisorctl status postgres redis backend frontend | grep -E "(postgres|redis|backend|frontend)"

echo ""
echo "💡 TIP: Add this script to supervisor as a pre-start hook to run automatically on container restart"
