// 11 personas from docs/COPILOT_PROMPT_CATALOG.md, with the avatar/accent map from
// nivesh_copilot_figma_spec.md §5. The catalog is the source of truth for IDs.

export const PERSONAS = [
  {
    id: "salaried_beginner",
    name: "Salaried Beginner",
    avatarIcon: "sprout",
    accent: "saffron",
    tagline: "Plain-language guidance with FD-comparable returns and one action at a time.",
    taglineHighlight: "vs FD return",
    heroQuestion: "Is my portfolio well diversified?",
    heroCategory: "risk",
  },
  {
    id: "mf_focused",
    name: "Mutual Fund Investor",
    avatarIcon: "bar-chart",
    accent: "saffron",
    tagline: "You hold 11 funds across 4 AMCs. We'll focus on overlap, fund quality, and expense-ratio leakage.",
    taglineHighlight: "11 funds across 4 AMCs",
    heroQuestion: "Do you have too many mutual funds?",
    heroCategory: "health",
  },
  {
    id: "direct_equity",
    name: "Direct Equity Investor",
    avatarIcon: "trending-up",
    accent: "gold",
    tagline: "Valuation and fundamentals depth, sector views, and concentration discipline.",
    taglineHighlight: "valuation focus",
    heroQuestion: "Which stocks are overvalued?",
    heroCategory: "performance",
  },
  {
    id: "hni",
    name: "High Net Worth Investor",
    avatarIcon: "diamond",
    accent: "indigo",
    tagline: "Multi-asset wealth with tax, estate, and alternative-asset overlays.",
    taglineHighlight: "₹2.4 Cr · multi-asset",
    heroQuestion: "Is my wealth allocation optimal?",
    heroCategory: "risk",
  },
  {
    id: "retirement_planner",
    name: "Retirement Planner",
    avatarIcon: "clock",
    accent: "crimson",
    tagline: "Income, withdrawal, and inflation lens with downside emphasis.",
    taglineHighlight: "income years left",
    heroQuestion: "Will my investments be enough?",
    heroCategory: "goal",
  },
  {
    id: "parents_for_kids",
    name: "Parents Planning",
    avatarIcon: "graduation",
    accent: "moss",
    tagline: "Goal-progress first, shortfall surfacing, insurance overlay.",
    taglineHighlight: "₹X / Y goal",
    heroQuestion: "Is the education corpus on track?",
    heroCategory: "goal",
  },
  {
    id: "tax_conscious",
    name: "Tax-Conscious Investor",
    avatarIcon: "calculator",
    accent: "indigo",
    tagline: "Tax-impact lens on every recommendation, FY-aware harvesting.",
    taglineHighlight: "₹X LTCG estimate",
    heroQuestion: "What are my unrealized gains?",
    heroCategory: "tax",
  },
  {
    id: "conservative",
    name: "Conservative Investor",
    avatarIcon: "shield",
    accent: "crimson",
    tagline: "Downside-first, FD-comparable framing, debt-and-hybrid focus.",
    taglineHighlight: "X% in equity",
    heroQuestion: "Is my portfolio too aggressive?",
    heroCategory: "risk",
  },
  {
    id: "active_trader",
    name: "Active Trader",
    avatarIcon: "activity",
    accent: "gold",
    tagline: "Realized P&L, momentum, sector rotation, position-level depth.",
    taglineHighlight: "X trades · ₹Y P&L",
    heroQuestion: "Best returns this quarter?",
    heroCategory: "performance",
  },
  {
    id: "nri_global",
    name: "NRI / Global Investor",
    avatarIcon: "globe",
    accent: "indigo",
    tagline: "Currency, geography mix, and tax-treaty hints.",
    taglineHighlight: "X% INR · Y% USD",
    heroQuestion: "How India-focused am I?",
    heroCategory: "risk",
  },
  {
    id: "universal",
    name: "Investor",
    avatarIcon: "compass",
    accent: "saffron",
    tagline: "Personalize this experience by picking a persona — answers get sharper.",
    taglineHighlight: null,
    heroQuestion: "Is my portfolio healthy?",
    heroCategory: "health",
  },
];

export function getPersona(id) {
  return PERSONAS.find((p) => p.id === id) || PERSONAS.find((p) => p.id === "universal");
}
