import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from "react-router-dom";
import { ChevronRight } from "lucide-react";
import { cn } from "@/lib/utils";
import { formatINR, formatPct } from "@/lib/formatters";
/**
 * Holdings table — desktop. On mobile this collapses to a stacked list.
 * Click row → /funds/:id.
 */
export function HoldingsTable({ holdings, className }) {
    const navigate = useNavigate();
    return (_jsxs("div", { className: cn("rounded-lg bg-surface-1 border border-hairline overflow-hidden", className), children: [_jsxs("table", { className: "hidden sm:table w-full text-sm", children: [_jsx("thead", { children: _jsx("tr", { className: "border-b border-hairline", children: ["Fund", "Category", "Units", "Market value", "P&L", "1Y", ""].map((h) => (_jsx("th", { className: "font-mono text-[10px] uppercase tracking-[.12em] text-ink-3 font-normal text-left px-5 py-3", children: h }, h))) }) }), _jsx("tbody", { children: holdings.map((h) => (_jsxs("tr", { onClick: () => navigate(`/funds/${h.fundId}`), className: "border-t border-hairline hover:bg-surface-2 cursor-pointer transition-colors", children: [_jsxs("td", { className: "px-5 py-4 align-top", children: [_jsx("div", { className: "font-medium text-[14px]", children: h.fund.name }), _jsx("div", { className: "font-mono text-[10.5px] text-ink-3 mt-1", children: h.fund.amc })] }), _jsx("td", { className: "px-5 py-4 align-top", children: _jsx("span", { className: "font-mono text-[11px] uppercase tracking-[.06em] text-ink-2", children: h.fund.category.replace("-", " ") }) }), _jsx("td", { className: "px-5 py-4 align-top font-mono num text-[13px] text-ink-2", children: h.units.toFixed(2) }), _jsx("td", { className: "px-5 py-4 align-top font-mono num text-[13px]", children: formatINR(h.marketValue) }), _jsxs("td", { className: "px-5 py-4 align-top font-mono num text-[13px] text-pos", children: ["+", formatINR(h.unrealizedPnl, { compact: true }), _jsxs("span", { className: "text-ink-3 text-[11px] ml-1", children: ["(", formatPct(h.unrealizedPnlPct, { signed: true }), ")"] })] }), _jsx("td", { className: "px-5 py-4 align-top font-mono num text-[13px] text-pos", children: formatPct(h.returns.y1, { signed: true }) }), _jsx("td", { className: "px-5 py-4 align-top text-ink-3", children: _jsx(ChevronRight, { className: "h-4 w-4" }) })] }, h.id))) })] }), _jsx("ul", { className: "sm:hidden divide-y divide-[rgb(var(--line)/0.10)]", children: holdings.map((h) => (_jsxs("li", { onClick: () => navigate(`/funds/${h.fundId}`), className: "px-5 py-4 active:bg-surface-2", children: [_jsxs("div", { className: "flex items-baseline gap-2", children: [_jsx("span", { className: "font-medium text-[14px]", children: h.fund.name }), _jsx("span", { className: "ml-auto font-mono num text-[13px]", children: formatINR(h.marketValue, { compact: true }) })] }), _jsxs("div", { className: "flex items-baseline gap-2 mt-1", children: [_jsx("span", { className: "font-mono text-[10.5px] uppercase tracking-[.06em] text-ink-3", children: h.fund.category.replace("-", " ") }), _jsx("span", { className: "ml-auto font-mono text-[11px] text-pos", children: formatPct(h.returns.y1, { signed: true }) })] })] }, h.id))) })] }));
}
